 
****************************************
Report : resources
Design : ZUMA
Version: O-2018.06
Date   : Fri Oct  9 04:00:50 2026
****************************************


Resource Report for this hierarchy in file ../01_RTL/ZUMA.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| add_x_2        | DW01_add       | width=8    | add_127 (ZUMA.v:127)       |
| ash_3          | DW_leftsh      | A_width=32 | sll_136 (ZUMA.v:136)       |
|                |                | SH_width=5 |                            |
| ash_4          | DW_leftsh      | A_width=8  | sll_137 (ZUMA.v:137)       |
|                |                | SH_width=3 |                            |
| ash_5          | DW_leftsh      | A_width=32 | sll_144 (ZUMA.v:144)       |
|                |                | SH_width=5 |                            |
| ash_6          | DW_leftsh      | A_width=8  | sll_145 (ZUMA.v:145)       |
|                |                | SH_width=3 |                            |
| add_x_7        | DW01_add       | width=3    | add_166_S2 (ZUMA.v:166)    |
| gte_x_66       | DW_cmp         | width=8    | gte_178 (ZUMA.v:178)       |
| ash_67         | DW_leftsh      | A_width=8  | sll_196 (ZUMA.v:196)       |
|                |                | SH_width=3 |                            |
| ash_68         | DW_leftsh      | A_width=32 | sll_208 (ZUMA.v:208)       |
|                |                | SH_width=5 |                            |
| ash_69         | DW_leftsh      | A_width=8  | sll_209 (ZUMA.v:209)       |
|                |                | SH_width=3 |                            |
| eq_x_77        | DW_cmp         | width=3    | eq_290 (ZUMA.v:290)        |
| eq_x_78        | DW_cmp         | width=3    | eq_291 (ZUMA.v:291)        |
| eq_x_79        | DW_cmp         | width=3    | eq_292 (ZUMA.v:292)        |
| eq_x_80        | DW_cmp         | width=3    | eq_293 (ZUMA.v:293)        |
| eq_x_81        | DW_cmp         | width=3    | eq_295 (ZUMA.v:295)        |
| eq_x_82        | DW_cmp         | width=3    | eq_296 (ZUMA.v:296)        |
| eq_x_83        | DW_cmp         | width=3    | eq_297 (ZUMA.v:297)        |
| eq_x_84        | DW_cmp         | width=3    | eq_298 (ZUMA.v:298)        |
| eq_x_85        | DW_cmp         | width=3    | eq_299 (ZUMA.v:299)        |
| eq_x_86        | DW_cmp         | width=3    | eq_300 (ZUMA.v:300)        |
| sub_x_100      | DW01_sub       | width=8    | sub_352 (ZUMA.v:352)       |
| gte_x_102      | DW_cmp         | width=8    | gte_353 (ZUMA.v:353)       |
| sub_x_103      | DW01_sub       | width=8    | sub_353 (ZUMA.v:353)       |
| sub_x_105      | DW01_sub       | width=8    | sub_354 (ZUMA.v:354)       |
| add_x_107      | DW01_add       | width=8    | add_359 (ZUMA.v:359)       |
| add_x_109      | DW01_add       | width=8    | add_360 (ZUMA.v:360)       |
| add_x_111      | DW01_add       | width=8    | add_361 (ZUMA.v:361)       |
| add_x_113      | DW01_add       | width=8    | add_362 (ZUMA.v:362)       |
| eq_x_115       | DW_cmp         | width=3    | eq_394 (ZUMA.v:394)        |
| eq_x_116       | DW_cmp         | width=3    | eq_395 (ZUMA.v:395)        |
| gte_x_117      | DW_cmp         | width=9    | gte_396 (ZUMA.v:396)       |
| eq_x_118       | DW_cmp         | width=3    | eq_396 (ZUMA.v:396)        |
| lte_x_119      | DW_cmp         | width=7    | lte_419 (ZUMA.v:419)       |
| lt_x_120       | DW_cmp         | width=8    | lt_424 (ZUMA.v:424)        |
| sub_x_125      | DW01_sub       | width=9    | sub_435 (ZUMA.v:435)       |
| lte_x_136      | DW_cmp         | width=4    | lte_509 (ZUMA.v:509)       |
| lte_x_137      | DW_cmp         | width=4    | lte_509_G2 (ZUMA.v:509)    |
| lte_x_138      | DW_cmp         | width=4    | lte_509_G3 (ZUMA.v:509)    |
| lte_x_139      | DW_cmp         | width=4    | lte_509_G4 (ZUMA.v:509)    |
| lte_x_140      | DW_cmp         | width=4    | lte_509_G5 (ZUMA.v:509)    |
| lte_x_141      | DW_cmp         | width=4    | lte_509_G6 (ZUMA.v:509)    |
| lte_x_142      | DW_cmp         | width=4    | lte_509_G7 (ZUMA.v:509)    |
| lte_x_143      | DW_cmp         | width=4    | lte_509_G8 (ZUMA.v:509)    |
| lte_x_144      | DW_cmp         | width=4    | lte_509_G9 (ZUMA.v:509)    |
| lte_x_145      | DW_cmp         | width=4    | lte_509_G10 (ZUMA.v:509)   |
| lte_x_146      | DW_cmp         | width=4    | lte_509_G11 (ZUMA.v:509)   |
| lte_x_147      | DW_cmp         | width=4    | lte_509_G12 (ZUMA.v:509)   |
| lte_x_148      | DW_cmp         | width=4    | lte_509_G13 (ZUMA.v:509)   |
| lte_x_149      | DW_cmp         | width=4    | lte_509_G14 (ZUMA.v:509)   |
| lte_x_150      | DW_cmp         | width=4    | lte_509_G15 (ZUMA.v:509)   |
| lte_x_151      | DW_cmp         | width=4    | lte_509_G16 (ZUMA.v:509)   |
| eq_x_152       | DW_cmp         | width=3    | eq_577 (ZUMA.v:577)        |
| eq_x_153       | DW_cmp         | width=3    | eq_578 (ZUMA.v:578)        |
| eq_x_154       | DW_cmp         | width=3    | eq_579 (ZUMA.v:579)        |
| ne_x_155       | DW_cmp         | width=3    | ne_589 (ZUMA.v:589)        |
| gte_x_156      | DW_cmp         | width=9    | gte_591 (ZUMA.v:591)       |
| gte_x_157      | DW_cmp         | width=9    | gte_592 (ZUMA.v:592)       |
| gte_x_158      | DW_cmp         | width=9    | gte_593 (ZUMA.v:593)       |
| ne_x_159       | DW_cmp         | width=3    | ne_594 (ZUMA.v:594)        |
| ne_x_160       | DW_cmp         | width=3    | ne_595 (ZUMA.v:595)        |
| gte_x_210      | DW_cmp         | width=3    | gte_167_I2_I3 (ZUMA.v:167) |
|                |                |            | gte_167_I3_I2 (ZUMA.v:167) |
|                |                |            | gte_167_I4 (ZUMA.v:167)    |
|                |                |            | gte_167_I4_I1 (ZUMA.v:167) |
| gte_x_211      | DW_cmp         | width=3    | gte_167_I2_I4 (ZUMA.v:167) |
|                |                |            | gte_167_I3_I3 (ZUMA.v:167) |
|                |                |            | gte_167_I4_I2 (ZUMA.v:167) |
|                |                |            | gte_167_I5 (ZUMA.v:167)    |
|                |                |            | gte_167_I5_I1 (ZUMA.v:167) |
| gte_x_212      | DW_cmp         | width=3    | gte_167_I2_I5 (ZUMA.v:167) |
|                |                |            | gte_167_I3_I4 (ZUMA.v:167) |
|                |                |            | gte_167_I4_I3 (ZUMA.v:167) |
|                |                |            | gte_167_I5_I2 (ZUMA.v:167) |
|                |                |            | gte_167_I6 (ZUMA.v:167)    |
|                |                |            | gte_167_I6_I1 (ZUMA.v:167) |
| gte_x_213      | DW_cmp         | width=3    | gte_167_I2_I6 (ZUMA.v:167) |
|                |                |            | gte_167_I3_I5 (ZUMA.v:167) |
|                |                |            | gte_167_I4_I4 (ZUMA.v:167) |
|                |                |            | gte_167_I5_I3 (ZUMA.v:167) |
|                |                |            | gte_167_I6_I2 (ZUMA.v:167) |
|                |                |            | gte_167_I7 (ZUMA.v:167)    |
|                |                |            | gte_167_I7_I1 (ZUMA.v:167) |
| gte_x_214      | DW_cmp         | width=3    | gte_167_I2_I7 (ZUMA.v:167) |
|                |                |            | gte_167_I3_I6 (ZUMA.v:167) |
|                |                |            | gte_167_I4_I5 (ZUMA.v:167) |
|                |                |            | gte_167_I5_I4 (ZUMA.v:167) |
|                |                |            | gte_167_I6_I3 (ZUMA.v:167) |
|                |                |            | gte_167_I7_I2 (ZUMA.v:167) |
|                |                |            | gte_167_I8 (ZUMA.v:167)    |
|                |                |            | gte_167_I8_I1 (ZUMA.v:167) |
| gte_x_215      | DW_cmp         | width=3    | gte_167_I2_I8 (ZUMA.v:167) |
|                |                |            | gte_167_I3_I7 (ZUMA.v:167) |
|                |                |            | gte_167_I4_I6 (ZUMA.v:167) |
|                |                |            | gte_167_I5_I5 (ZUMA.v:167) |
|                |                |            | gte_167_I6_I4 (ZUMA.v:167) |
|                |                |            | gte_167_I7_I3 (ZUMA.v:167) |
|                |                |            | gte_167_I8_I2 (ZUMA.v:167) |
| gte_x_216      | DW_cmp         | width=3    | gte_167_I3_I8 (ZUMA.v:167) |
|                |                |            | gte_167_I4_I7 (ZUMA.v:167) |
|                |                |            | gte_167_I5_I6 (ZUMA.v:167) |
|                |                |            | gte_167_I6_I5 (ZUMA.v:167) |
|                |                |            | gte_167_I7_I4 (ZUMA.v:167) |
|                |                |            | gte_167_I8_I3 (ZUMA.v:167) |
| lt_x_218       | DW_cmp         | width=4    | lt_505 (ZUMA.v:505)        |
|                |                |            | lt_507 (ZUMA.v:507)        |
| lt_x_219       | DW_cmp         | width=4    | lt_505_G4 (ZUMA.v:505)     |
|                |                |            | lt_507_G4 (ZUMA.v:507)     |
| lt_x_220       | DW_cmp         | width=4    | lt_505_G6 (ZUMA.v:505)     |
|                |                |            | lt_507_G6 (ZUMA.v:507)     |
| lt_x_221       | DW_cmp         | width=4    | lt_505_G7 (ZUMA.v:505)     |
|                |                |            | lt_507_G7 (ZUMA.v:507)     |
| lt_x_222       | DW_cmp         | width=4    | lt_505_G8 (ZUMA.v:505)     |
|                |                |            | lt_507_G8 (ZUMA.v:507)     |
| lt_x_223       | DW_cmp         | width=4    | lt_505_G10 (ZUMA.v:505)    |
|                |                |            | lt_507_G10 (ZUMA.v:507)    |
| lt_x_224       | DW_cmp         | width=4    | lt_505_G11 (ZUMA.v:505)    |
|                |                |            | lt_507_G11 (ZUMA.v:507)    |
| lt_x_225       | DW_cmp         | width=4    | lt_505_G12 (ZUMA.v:505)    |
|                |                |            | lt_507_G12 (ZUMA.v:507)    |
| lt_x_226       | DW_cmp         | width=4    | lt_505_G13 (ZUMA.v:505)    |
|                |                |            | lt_507_G13 (ZUMA.v:507)    |
| lt_x_227       | DW_cmp         | width=4    | lt_505_G14 (ZUMA.v:505)    |
|                |                |            | lt_507_G14 (ZUMA.v:507)    |
| lt_x_228       | DW_cmp         | width=4    | lt_505_G15 (ZUMA.v:505)    |
|                |                |            | lt_507_G15 (ZUMA.v:507)    |
| lt_x_229       | DW_cmp         | width=4    | lt_505_G16 (ZUMA.v:505)    |
|                |                |            | lt_507_G16 (ZUMA.v:507)    |
| sub_x_14       | DW01_sub       | width=3    | sub_167_S2_2_I2_I7 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I3_I6 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I4_I5 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5_I4 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6_I3 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7_I2 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8 (ZUMA.v:167) |
               |                |            | sub_167_S2_2_I8_I1 (ZUMA.v:167) |
| sub_x_12       | DW01_sub       | width=3    | sub_167_S2_2_I2_I5 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I3_I4 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I4_I3 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5_I2 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6 (ZUMA.v:167) |
               |                |            | sub_167_S2_2_I6_I1 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7_I8 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8_I7 (ZUMA.v:167) |
| sub_x_13       | DW01_sub       | width=3    | sub_167_S2_2_I2_I6 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I3_I5 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I4_I4 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5_I3 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6_I2 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7 (ZUMA.v:167) |
               |                |            | sub_167_S2_2_I7_I1 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8_I8 (ZUMA.v:167) |
| sub_x_10       | DW01_sub       | width=3    | sub_167_S2_2_I2_I3 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I3_I2 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I4 (ZUMA.v:167) |
               |                |            | sub_167_S2_2_I4_I1 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5_I8 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6_I7 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7_I6 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8_I5 (ZUMA.v:167) |
| sub_x_11       | DW01_sub       | width=3    | sub_167_S2_2_I2_I4 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I3_I3 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I4_I2 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5 (ZUMA.v:167) |
               |                |            | sub_167_S2_2_I5_I1 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6_I8 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7_I7 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8_I6 (ZUMA.v:167) |
| sub_x_15       | DW01_sub       | width=3    | sub_167_S2_2_I2_I8 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I3_I7 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I4_I6 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5_I5 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6_I4 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7_I3 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8_I2 (ZUMA.v:167) |
| sub_x_16       | DW01_sub       | width=3    | sub_167_S2_2_I3_I8 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I4_I7 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5_I6 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6_I5 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7_I4 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8_I3 (ZUMA.v:167) |
| sub_x_17       | DW01_sub       | width=3    | sub_167_S2_2_I4_I8 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I5_I7 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I6_I6 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I7_I5 (ZUMA.v:167) |
            |                |            | sub_167_S2_2_I8_I4 (ZUMA.v:167) |
| add_x_9        | DW01_dec       | width=3    | add_166_S2_I2_I2 (ZUMA.v:166) |
              |                |            | add_166_S2_I3 (ZUMA.v:166) |
|                |                |            | add_166_S2_I3_I1 (ZUMA.v:166) |
| add_x_1        | DW01_inc       | width=9    | add_126 (ZUMA.v:126)       |
|                |                |            | add_481_S2 (ZUMA.v:481)    |
| sub_x_96       | DW01_dec       | width=8    | sub_338 (ZUMA.v:338)       |
|                |                |            | sub_351 (ZUMA.v:351)       |
| add_x_8        | DW01_add       | width=3    | add_166_S2_I2 (ZUMA.v:166) |
|                |                |            | add_166_S2_I2_I1 (ZUMA.v:166) |
| DP_OP_691J1_122_2714            |            |                            |
|                | DP_OP_691J1_122_2714 |      |                            |
| DP_OP_692J1_123_2714            |            |                            |
|                | DP_OP_692J1_123_2714 |      |                            |
| DP_OP_693J1_124_8018            |            |                            |
|                | DP_OP_693J1_124_8018 |      |                            |
| DP_OP_694J1_125_8018            |            |                            |
|                | DP_OP_694J1_125_8018 |      |                            |
| DP_OP_695J1_126_8018            |            |                            |
|                | DP_OP_695J1_126_8018 |      |                            |
| DP_OP_696J1_127_5271            |            |                            |
|                | DP_OP_696J1_127_5271 |      |                            |
| DP_OP_623J1_132_5591            |            |                            |
|                | DP_OP_623J1_132_5591 |      |                            |
| DP_OP_624J1_133_5591            |            |                            |
|                | DP_OP_624J1_133_5591 |      |                            |
| DP_OP_659J1_141_2092            |            |                            |
|                | DP_OP_659J1_141_2092 |      |                            |
| DP_OP_660J1_142_1013            |            |                            |
|                | DP_OP_660J1_142_1013 |      |                            |
| DP_OP_689J1_146_7630            |            |                            |
|                | DP_OP_689J1_146_7630 |      |                            |
| DP_OP_677J1_143_8359            |            |                            |
|                | DP_OP_677J1_143_8359 |      |                            |
| DP_OP_658_149_7092              |            |                            |
|                | DP_OP_658_149_7092 |        |                            |
| DP_OP_634J1_134_267             |            |                            |
|                | DP_OP_634J1_134_267 |       |                            |
| DP_OP_382J1_128_9039            |            |                            |
|                | DP_OP_382J1_128_9039 |      |                            |
=============================================================================

Datapath Report for DP_OP_691J1_122_2714
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_691J1_122_2714 | sub_122 (ZUMA.v:122) eq_153 (ZUMA.v:153)            |
|                      | eq_409 (ZUMA.v:409)                                 |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - $unsigned(1'b1) (ZUMA.v:122)        |
| O2    | PO   | Unsigned | 1     | I2 == $unsigned(O1) (ZUMA.v:153)         |
| O3    | PO   | Unsigned | 1     | I3 == $unsigned(O1) (ZUMA.v:409)         |
==============================================================================

Datapath Report for DP_OP_692J1_123_2714
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_692J1_123_2714 | sub_123 (ZUMA.v:123) eq_154 (ZUMA.v:154)            |
|                      | eq_410 (ZUMA.v:410)                                 |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| I3    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - $unsigned(2'b10) (ZUMA.v:123)       |
| O2    | PO   | Unsigned | 1     | I2 == $unsigned(O1) (ZUMA.v:154)         |
| O3    | PO   | Unsigned | 1     | I3 == $unsigned(O1) (ZUMA.v:410)         |
==============================================================================

Datapath Report for DP_OP_693J1_124_8018
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_693J1_124_8018 | sub_124 (ZUMA.v:124) eq_155 (ZUMA.v:155)            |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - $unsigned(2'b11) (ZUMA.v:124)       |
| O2    | PO   | Unsigned | 1     | I2 == $unsigned(O1) (ZUMA.v:155)         |
==============================================================================

Datapath Report for DP_OP_694J1_125_8018
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_694J1_125_8018 | sub_125 (ZUMA.v:125) eq_156 (ZUMA.v:156)            |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - $unsigned(3'b100) (ZUMA.v:125)      |
| O2    | PO   | Unsigned | 1     | I2 == $unsigned(O1) (ZUMA.v:156)         |
==============================================================================

Datapath Report for DP_OP_695J1_126_8018
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_695J1_126_8018 | sub_356 (ZUMA.v:356) eq_358 (ZUMA.v:358)            |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - $unsigned(3'b101) (ZUMA.v:356)      |
| O2    | PO   | Unsigned | 1     | I2 == $unsigned(O1) (ZUMA.v:358)         |
==============================================================================

Datapath Report for DP_OP_696J1_127_5271
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_696J1_127_5271 | add_427 (ZUMA.v:427) sub_425 (ZUMA.v:425)           |
|                      | sub_425_2 (ZUMA.v:425)                              |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Unsigned | 9     | I1 + $unsigned(1'b1) ( ZUMA.v:425 ZUMA.v:427 ) |
| O2    | PO   | Signed   | 9     | I2 - O1 (ZUMA.v:425)                     |
==============================================================================

Datapath Report for DP_OP_623J1_132_5591
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_623J1_132_5591 | sub_179 (ZUMA.v:179)                                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 8     | I1 - $unsigned(3'b100) (ZUMA.v:179)      |
==============================================================================

Datapath Report for DP_OP_624J1_133_5591
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_624J1_133_5591 | add_189 (ZUMA.v:189)                                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Unsigned | 8     | I1 + $unsigned(2'b11) (ZUMA.v:189)       |
==============================================================================

Datapath Report for DP_OP_659J1_141_2092
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_659J1_141_2092 | sub_357 (ZUMA.v:357)                                |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 9     |                                          |
| O1    | PO   | Signed   | 9     | I1 - $unsigned(3'b110) (ZUMA.v:357)      |
==============================================================================

Datapath Report for DP_OP_660J1_142_1013
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_660J1_142_1013 | add_399 (ZUMA.v:399) sub_623_S2 (ZUMA.v:623)        |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 2     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| I3    | PI   | Signed   | 9     |                                          |
| O1    | PO   | Signed   | 9     | -I1 - I2 + I3 ( ZUMA.v:399 ZUMA.v:623 )  |
==============================================================================

Datapath Report for DP_OP_689J1_146_7630
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_689J1_146_7630 | add_411 (ZUMA.v:411) add_412 (ZUMA.v:412)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| O1    | PO   | Unsigned | 8     | I1 + I2 ( ZUMA.v:411 ZUMA.v:412 )        |
==============================================================================

Datapath Report for DP_OP_677J1_143_8359
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_677J1_143_8359 | sub_406 (ZUMA.v:406) sub_407 (ZUMA.v:407)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 8     |                                          |
| I2    | PI   | Unsigned | 2     |                                          |
| O1    | PO   | Signed   | 8     | I1 - I2 ( ZUMA.v:406 ZUMA.v:407 )        |
==============================================================================

Datapath Report for DP_OP_658_149_7092
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_658_149_7092   | add_436 (ZUMA.v:436) add_337 (ZUMA.v:337)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Unsigned | 8     | I1 + $unsigned(1'b1) ( ZUMA.v:337 ZUMA.v:436 ) |
==============================================================================

Datapath Report for DP_OP_634J1_134_267
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_634J1_134_267  | sub_185 (ZUMA.v:185) sub_190 (ZUMA.v:190)           |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 9     |                                          |
| I2    | PI   | Unsigned | 8     |                                          |
| O1    | PO   | Signed   | 9     | I1 - I2 ( ZUMA.v:185 ZUMA.v:190 )        |
==============================================================================

Datapath Report for DP_OP_382J1_128_9039
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_382J1_128_9039 | sub_777_S2 (ZUMA.v:777) add_780_S2 (ZUMA.v:780)     |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Signed   | 7     |                                          |
| I2    | PI   | Unsigned | 1     |                                          |
| O1    | PO   | Signed   | 7     | addsub(I1,1,I2) ( ZUMA.v:777 ZUMA.v:780 ) |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'sub_167_S2_2_I7_I1 (ZUMA.v:167) sub_167_S2_2_I6_I2 (ZUMA.v:167) sub_167_S2_2_I5_I3 (ZUMA.v:167) sub_167_S2_2_I4_I4 (ZUMA.v:167) sub_167_S2_2_I3_I5 (ZUMA.v:167) sub_167_S2_2_I2_I6 (ZUMA.v:167) sub_167_S2_2_I7 (ZUMA.v:167) sub_167_S2_2_I8_I8 (ZUMA.v:167)' in design 'ZUMA' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8896 (ZUMA.v:166)'.  (HDL-120)

Information: Operator associated with resources 'sub_167_S2_2_I6_I1 (ZUMA.v:167) sub_167_S2_2_I5_I2 (ZUMA.v:167) sub_167_S2_2_I4_I3 (ZUMA.v:167) sub_167_S2_2_I3_I4 (ZUMA.v:167) sub_167_S2_2_I2_I5 (ZUMA.v:167) sub_167_S2_2_I6 (ZUMA.v:167) sub_167_S2_2_I8_I7 (ZUMA.v:167) sub_167_S2_2_I7_I8 (ZUMA.v:167)' in design 'ZUMA' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8895 (ZUMA.v:166)'.  (HDL-120)

Information: Operator associated with resources 'sub_167_S2_2_I5_I1 (ZUMA.v:167) sub_167_S2_2_I4_I2 (ZUMA.v:167) sub_167_S2_2_I3_I3 (ZUMA.v:167) sub_167_S2_2_I2_I4 (ZUMA.v:167) sub_167_S2_2_I5 (ZUMA.v:167) sub_167_S2_2_I8_I6 (ZUMA.v:167) sub_167_S2_2_I7_I7 (ZUMA.v:167) sub_167_S2_2_I6_I8 (ZUMA.v:167)' in design 'ZUMA' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8894 (ZUMA.v:166)'.  (HDL-120)

Information: Operator associated with resources 'sub_167_S2_2_I4_I1 (ZUMA.v:167) sub_167_S2_2_I3_I2 (ZUMA.v:167) sub_167_S2_2_I2_I3 (ZUMA.v:167) sub_167_S2_2_I4 (ZUMA.v:167) sub_167_S2_2_I8_I5 (ZUMA.v:167) sub_167_S2_2_I7_I6 (ZUMA.v:167) sub_167_S2_2_I6_I7 (ZUMA.v:167) sub_167_S2_2_I5_I8 (ZUMA.v:167)' in design 'ZUMA' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8893 (ZUMA.v:166)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| add_x_2            | DW01_add         | apparch (area)     |                |
| ash_3              | DW_leftsh        | astr (area)        |                |
| ash_4              | DW_leftsh        | astr (area)        |                |
| ash_5              | DW_leftsh        | astr (area)        |                |
| ash_6              | DW_leftsh        | astr (area)        |                |
| add_x_7            | DW01_add         | apparch (area)     |                |
| gte_x_66           | DW_cmp           | apparch (area)     |                |
| ash_67             | DW_leftsh        | astr (area)        |                |
| ash_68             | DW_leftsh        | astr (area)        |                |
| ash_69             | DW_leftsh        | astr (area)        |                |
| eq_x_77            | DW_cmp           | apparch (area)     |                |
| eq_x_78            | DW_cmp           | apparch (area)     |                |
| eq_x_79            | DW_cmp           | apparch (area)     |                |
| eq_x_80            | DW_cmp           | apparch (area)     |                |
| eq_x_81            | DW_cmp           | apparch (area)     |                |
| eq_x_82            | DW_cmp           | apparch (area)     |                |
| eq_x_83            | DW_cmp           | apparch (area)     |                |
| eq_x_84            | DW_cmp           | apparch (area)     |                |
| eq_x_85            | DW_cmp           | apparch (area)     |                |
| eq_x_86            | DW_cmp           | apparch (area)     |                |
| sub_x_100          | DW01_sub         | apparch (area)     |                |
| gte_x_102          | DW_cmp           | apparch (area)     |                |
| sub_x_103          | DW01_sub         | apparch (area)     |                |
| sub_x_105          | DW01_sub         | apparch (area)     |                |
| add_x_107          | DW01_add         | apparch (area)     |                |
| add_x_109          | DW01_add         | apparch (area)     |                |
| add_x_111          | DW01_add         | apparch (area)     |                |
| add_x_113          | DW01_add         | apparch (area)     |                |
| eq_x_115           | DW_cmp           | apparch (area)     |                |
| eq_x_116           | DW_cmp           | apparch (area)     |                |
| gte_x_117          | DW_cmp           | apparch (area)     |                |
| eq_x_118           | DW_cmp           | apparch (area)     |                |
| lte_x_119          | DW_cmp           | apparch (area)     |                |
| lt_x_120           | DW_cmp           | apparch (area)     |                |
| sub_x_125          | DW01_sub         | apparch (area)     |                |
| lte_x_136          | DW_cmp           | apparch (area)     |                |
| lte_x_137          | DW_cmp           | apparch (area)     |                |
| lte_x_138          | DW_cmp           | apparch (area)     |                |
| lte_x_139          | DW_cmp           | apparch (area)     |                |
| lte_x_140          | DW_cmp           | apparch (area)     |                |
| lte_x_141          | DW_cmp           | apparch (area)     |                |
| lte_x_142          | DW_cmp           | apparch (area)     |                |
| lte_x_143          | DW_cmp           | apparch (area)     |                |
| lte_x_144          | DW_cmp           | apparch (area)     |                |
| lte_x_145          | DW_cmp           | apparch (area)     |                |
| lte_x_146          | DW_cmp           | apparch (area)     |                |
| lte_x_147          | DW_cmp           | apparch (area)     |                |
| lte_x_148          | DW_cmp           | apparch (area)     |                |
| lte_x_149          | DW_cmp           | apparch (area)     |                |
| lte_x_150          | DW_cmp           | apparch (area)     |                |
| lte_x_151          | DW_cmp           | apparch (area)     |                |
| eq_x_152           | DW_cmp           | apparch (area)     |                |
| eq_x_153           | DW_cmp           | apparch (area)     |                |
| eq_x_154           | DW_cmp           | apparch (area)     |                |
| ne_x_155           | DW_cmp           | apparch (area)     |                |
| gte_x_156          | DW_cmp           | apparch (area)     |                |
| gte_x_157          | DW_cmp           | apparch (area)     |                |
| gte_x_158          | DW_cmp           | apparch (area)     |                |
| ne_x_159           | DW_cmp           | apparch (area)     |                |
| ne_x_160           | DW_cmp           | apparch (area)     |                |
| gte_x_210          | DW_cmp           | apparch (area)     |                |
| gte_x_211          | DW_cmp           | apparch (area)     |                |
| gte_x_212          | DW_cmp           | apparch (area)     |                |
| gte_x_213          | DW_cmp           | apparch (area)     |                |
| gte_x_214          | DW_cmp           | apparch (area)     |                |
| gte_x_215          | DW_cmp           | apparch (area)     |                |
| gte_x_216          | DW_cmp           | apparch (area)     |                |
| lt_x_218           | DW_cmp           | apparch (area)     |                |
| lt_x_219           | DW_cmp           | apparch (area)     |                |
| lt_x_220           | DW_cmp           | apparch (area)     |                |
| lt_x_221           | DW_cmp           | apparch (area)     |                |
| lt_x_222           | DW_cmp           | apparch (area)     |                |
| lt_x_223           | DW_cmp           | apparch (area)     |                |
| lt_x_224           | DW_cmp           | apparch (area)     |                |
| lt_x_225           | DW_cmp           | apparch (area)     |                |
| lt_x_226           | DW_cmp           | apparch (area)     |                |
| lt_x_227           | DW_cmp           | apparch (area)     |                |
| lt_x_228           | DW_cmp           | apparch (area)     |                |
| lt_x_229           | DW_cmp           | apparch (area)     |                |
| sub_x_14           | DW01_sub         | apparch (area)     |                |
| sub_x_12           | DW01_sub         | apparch (area)     |                |
| sub_x_13           | DW01_sub         | apparch (area)     |                |
| sub_x_10           | DW01_sub         | apparch (area)     |                |
| sub_x_11           | DW01_sub         | apparch (area)     |                |
| sub_x_15           | DW01_sub         | apparch (area)     |                |
| sub_x_16           | DW01_sub         | apparch (area)     |                |
| sub_x_17           | DW01_sub         | apparch (area)     |                |
| add_x_9            | DW01_dec         | apparch (area)     |                |
| add_x_1            | DW01_inc         | apparch (area)     |                |
| sub_x_96           | DW01_dec         | apparch (area)     |                |
| add_x_8            | DW01_add         | apparch (area)     |                |
| DP_OP_691J1_122_2714                  |                    |                |
|                    | DP_OP_691J1_122_2714 | str (area,speed)                |
| DP_OP_692J1_123_2714                  |                    |                |
|                    | DP_OP_692J1_123_2714 | str (area)     |                |
| DP_OP_693J1_124_8018                  |                    |                |
|                    | DP_OP_693J1_124_8018 | str (area)     |                |
| DP_OP_694J1_125_8018                  |                    |                |
|                    | DP_OP_694J1_125_8018 | str (area)     |                |
| DP_OP_695J1_126_8018                  |                    |                |
|                    | DP_OP_695J1_126_8018 | str (area)     |                |
| DP_OP_696J1_127_5271                  |                    |                |
|                    | DP_OP_696J1_127_5271 | str (area)     |                |
| DP_OP_623J1_132_5591                  |                    |                |
|                    | DP_OP_623J1_132_5591 | str (area)     |                |
| DP_OP_624J1_133_5591                  |                    |                |
|                    | DP_OP_624J1_133_5591 | str (area)     |                |
| DP_OP_659J1_141_2092                  |                    |                |
|                    | DP_OP_659J1_141_2092 | str (area)     |                |
| DP_OP_660J1_142_1013                  |                    |                |
|                    | DP_OP_660J1_142_1013 | str (area)     |                |
| DP_OP_689J1_146_7630                  |                    |                |
|                    | DP_OP_689J1_146_7630 | str (area)     |                |
| DP_OP_677J1_143_8359                  |                    |                |
|                    | DP_OP_677J1_143_8359 | str (area)     |                |
| DP_OP_658_149_7092 | DP_OP_658_149_7092 | str (area,speed) |                |
| DP_OP_634J1_134_267                   |                    |                |
|                    | DP_OP_634J1_134_267 | str (area)      |                |
| DP_OP_382J1_128_9039                  |                    |                |
|                    | DP_OP_382J1_128_9039 | str (area)     |                |
===============================================================================

1
