//############################################################################
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//   (C) Copyright Laboratory System Integration and Silicon Implementation
//   All Right Reserved
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//
//   ICLAB 2026 Fall
//   Lab01 Exercise        : Out-of-Order Instruction Scheduling Solver
//   Author                : ICLAB TA
//
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//
//   File Name             : TESTBED.v
//   Module Name           : TESTBED
//   Release version       : V1.0 (Release Date: 2026-09)
//
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//############################################################################

`timescale 1ns/1ns

module TESTBED;

//============================================================================
// Connection wires
//============================================================================
wire         clk;
wire [95:0]  Inst_seq_I;
wire [47:0]  Inst_latency_I;
wire [23:0]  Inst_order_O;
wire [8:0]   Ex_cycle;

//============================================================================
// Waveform dump and gate-level timing annotation
//============================================================================
initial begin
  `ifdef RTL
    //$fsdbDumpfile("OISS.fsdb");
    //$fsdbDumpvars(0, "+mda");
    //$fsdbDumpvars();
  `endif

  `ifdef GATE
    $sdf_annotate("../02_SYN/Netlist/OISS_SYN.sdf", DUT_OISS);
    $fsdbDumpfile("OISS_SYN.fsdb");
    $fsdbDumpvars(0, "+mda");
    $fsdbDumpvars();
  `endif
end

//============================================================================
// Device under test
// The clock generated by PATTERN is used only for testbench synchronization
// and is intentionally not connected to the purely combinational OISS design.
//============================================================================
OISS DUT_OISS (
  .Inst_seq_I     (Inst_seq_I),
  .Inst_latency_I (Inst_latency_I),
  .Inst_order_O   (Inst_order_O),
  .Ex_cycle       (Ex_cycle)
);

//============================================================================
// Pattern generator and checker
//============================================================================
PATTERN My_PATTERN (
  .clk            (clk),
  .Inst_seq_I     (Inst_seq_I),
  .Inst_latency_I (Inst_latency_I),
  .Inst_order_O   (Inst_order_O),
  .Ex_cycle       (Ex_cycle)
);

endmodule
