###################################################################

# Created by write_sdc on Thu Sep 17 03:29:07 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {out[31]}]
set_load -pin_load 0.05 [get_ports {out[30]}]
set_load -pin_load 0.05 [get_ports {out[29]}]
set_load -pin_load 0.05 [get_ports {out[28]}]
set_load -pin_load 0.05 [get_ports {out[27]}]
set_load -pin_load 0.05 [get_ports {out[26]}]
set_load -pin_load 0.05 [get_ports {out[25]}]
set_load -pin_load 0.05 [get_ports {out[24]}]
set_load -pin_load 0.05 [get_ports {out[23]}]
set_load -pin_load 0.05 [get_ports {out[22]}]
set_load -pin_load 0.05 [get_ports {out[21]}]
set_load -pin_load 0.05 [get_ports {out[20]}]
set_load -pin_load 0.05 [get_ports {out[19]}]
set_load -pin_load 0.05 [get_ports {out[18]}]
set_load -pin_load 0.05 [get_ports {out[17]}]
set_load -pin_load 0.05 [get_ports {out[16]}]
set_load -pin_load 0.05 [get_ports {out[15]}]
set_load -pin_load 0.05 [get_ports {out[14]}]
set_load -pin_load 0.05 [get_ports {out[13]}]
set_load -pin_load 0.05 [get_ports {out[12]}]
set_load -pin_load 0.05 [get_ports {out[11]}]
set_load -pin_load 0.05 [get_ports {out[10]}]
set_load -pin_load 0.05 [get_ports {out[9]}]
set_load -pin_load 0.05 [get_ports {out[8]}]
set_load -pin_load 0.05 [get_ports {out[7]}]
set_load -pin_load 0.05 [get_ports {out[6]}]
set_load -pin_load 0.05 [get_ports {out[5]}]
set_load -pin_load 0.05 [get_ports {out[4]}]
set_load -pin_load 0.05 [get_ports {out[3]}]
set_load -pin_load 0.05 [get_ports {out[2]}]
set_load -pin_load 0.05 [get_ports {out[1]}]
set_load -pin_load 0.05 [get_ports {out[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports {Q[31]}]
set_max_capacitance 0.15 [get_ports {Q[30]}]
set_max_capacitance 0.15 [get_ports {Q[29]}]
set_max_capacitance 0.15 [get_ports {Q[28]}]
set_max_capacitance 0.15 [get_ports {Q[27]}]
set_max_capacitance 0.15 [get_ports {Q[26]}]
set_max_capacitance 0.15 [get_ports {Q[25]}]
set_max_capacitance 0.15 [get_ports {Q[24]}]
set_max_capacitance 0.15 [get_ports {Q[23]}]
set_max_capacitance 0.15 [get_ports {Q[22]}]
set_max_capacitance 0.15 [get_ports {Q[21]}]
set_max_capacitance 0.15 [get_ports {Q[20]}]
set_max_capacitance 0.15 [get_ports {Q[19]}]
set_max_capacitance 0.15 [get_ports {Q[18]}]
set_max_capacitance 0.15 [get_ports {Q[17]}]
set_max_capacitance 0.15 [get_ports {Q[16]}]
set_max_capacitance 0.15 [get_ports {Q[15]}]
set_max_capacitance 0.15 [get_ports {Q[14]}]
set_max_capacitance 0.15 [get_ports {Q[13]}]
set_max_capacitance 0.15 [get_ports {Q[12]}]
set_max_capacitance 0.15 [get_ports {Q[11]}]
set_max_capacitance 0.15 [get_ports {Q[10]}]
set_max_capacitance 0.15 [get_ports {Q[9]}]
set_max_capacitance 0.15 [get_ports {Q[8]}]
set_max_capacitance 0.15 [get_ports {Q[7]}]
set_max_capacitance 0.15 [get_ports {Q[6]}]
set_max_capacitance 0.15 [get_ports {Q[5]}]
set_max_capacitance 0.15 [get_ports {Q[4]}]
set_max_capacitance 0.15 [get_ports {Q[3]}]
set_max_capacitance 0.15 [get_ports {Q[2]}]
set_max_capacitance 0.15 [get_ports {Q[1]}]
set_max_capacitance 0.15 [get_ports {Q[0]}]
set_max_capacitance 0.15 [get_ports {K[31]}]
set_max_capacitance 0.15 [get_ports {K[30]}]
set_max_capacitance 0.15 [get_ports {K[29]}]
set_max_capacitance 0.15 [get_ports {K[28]}]
set_max_capacitance 0.15 [get_ports {K[27]}]
set_max_capacitance 0.15 [get_ports {K[26]}]
set_max_capacitance 0.15 [get_ports {K[25]}]
set_max_capacitance 0.15 [get_ports {K[24]}]
set_max_capacitance 0.15 [get_ports {K[23]}]
set_max_capacitance 0.15 [get_ports {K[22]}]
set_max_capacitance 0.15 [get_ports {K[21]}]
set_max_capacitance 0.15 [get_ports {K[20]}]
set_max_capacitance 0.15 [get_ports {K[19]}]
set_max_capacitance 0.15 [get_ports {K[18]}]
set_max_capacitance 0.15 [get_ports {K[17]}]
set_max_capacitance 0.15 [get_ports {K[16]}]
set_max_capacitance 0.15 [get_ports {K[15]}]
set_max_capacitance 0.15 [get_ports {K[14]}]
set_max_capacitance 0.15 [get_ports {K[13]}]
set_max_capacitance 0.15 [get_ports {K[12]}]
set_max_capacitance 0.15 [get_ports {K[11]}]
set_max_capacitance 0.15 [get_ports {K[10]}]
set_max_capacitance 0.15 [get_ports {K[9]}]
set_max_capacitance 0.15 [get_ports {K[8]}]
set_max_capacitance 0.15 [get_ports {K[7]}]
set_max_capacitance 0.15 [get_ports {K[6]}]
set_max_capacitance 0.15 [get_ports {K[5]}]
set_max_capacitance 0.15 [get_ports {K[4]}]
set_max_capacitance 0.15 [get_ports {K[3]}]
set_max_capacitance 0.15 [get_ports {K[2]}]
set_max_capacitance 0.15 [get_ports {K[1]}]
set_max_capacitance 0.15 [get_ports {K[0]}]
set_max_capacitance 0.15 [get_ports {V[31]}]
set_max_capacitance 0.15 [get_ports {V[30]}]
set_max_capacitance 0.15 [get_ports {V[29]}]
set_max_capacitance 0.15 [get_ports {V[28]}]
set_max_capacitance 0.15 [get_ports {V[27]}]
set_max_capacitance 0.15 [get_ports {V[26]}]
set_max_capacitance 0.15 [get_ports {V[25]}]
set_max_capacitance 0.15 [get_ports {V[24]}]
set_max_capacitance 0.15 [get_ports {V[23]}]
set_max_capacitance 0.15 [get_ports {V[22]}]
set_max_capacitance 0.15 [get_ports {V[21]}]
set_max_capacitance 0.15 [get_ports {V[20]}]
set_max_capacitance 0.15 [get_ports {V[19]}]
set_max_capacitance 0.15 [get_ports {V[18]}]
set_max_capacitance 0.15 [get_ports {V[17]}]
set_max_capacitance 0.15 [get_ports {V[16]}]
set_max_capacitance 0.15 [get_ports {V[15]}]
set_max_capacitance 0.15 [get_ports {V[14]}]
set_max_capacitance 0.15 [get_ports {V[13]}]
set_max_capacitance 0.15 [get_ports {V[12]}]
set_max_capacitance 0.15 [get_ports {V[11]}]
set_max_capacitance 0.15 [get_ports {V[10]}]
set_max_capacitance 0.15 [get_ports {V[9]}]
set_max_capacitance 0.15 [get_ports {V[8]}]
set_max_capacitance 0.15 [get_ports {V[7]}]
set_max_capacitance 0.15 [get_ports {V[6]}]
set_max_capacitance 0.15 [get_ports {V[5]}]
set_max_capacitance 0.15 [get_ports {V[4]}]
set_max_capacitance 0.15 [get_ports {V[3]}]
set_max_capacitance 0.15 [get_ports {V[2]}]
set_max_capacitance 0.15 [get_ports {V[1]}]
set_max_capacitance 0.15 [get_ports {V[0]}]
set_max_capacitance 0.15 [get_ports {out_weight[31]}]
set_max_capacitance 0.15 [get_ports {out_weight[30]}]
set_max_capacitance 0.15 [get_ports {out_weight[29]}]
set_max_capacitance 0.15 [get_ports {out_weight[28]}]
set_max_capacitance 0.15 [get_ports {out_weight[27]}]
set_max_capacitance 0.15 [get_ports {out_weight[26]}]
set_max_capacitance 0.15 [get_ports {out_weight[25]}]
set_max_capacitance 0.15 [get_ports {out_weight[24]}]
set_max_capacitance 0.15 [get_ports {out_weight[23]}]
set_max_capacitance 0.15 [get_ports {out_weight[22]}]
set_max_capacitance 0.15 [get_ports {out_weight[21]}]
set_max_capacitance 0.15 [get_ports {out_weight[20]}]
set_max_capacitance 0.15 [get_ports {out_weight[19]}]
set_max_capacitance 0.15 [get_ports {out_weight[18]}]
set_max_capacitance 0.15 [get_ports {out_weight[17]}]
set_max_capacitance 0.15 [get_ports {out_weight[16]}]
set_max_capacitance 0.15 [get_ports {out_weight[15]}]
set_max_capacitance 0.15 [get_ports {out_weight[14]}]
set_max_capacitance 0.15 [get_ports {out_weight[13]}]
set_max_capacitance 0.15 [get_ports {out_weight[12]}]
set_max_capacitance 0.15 [get_ports {out_weight[11]}]
set_max_capacitance 0.15 [get_ports {out_weight[10]}]
set_max_capacitance 0.15 [get_ports {out_weight[9]}]
set_max_capacitance 0.15 [get_ports {out_weight[8]}]
set_max_capacitance 0.15 [get_ports {out_weight[7]}]
set_max_capacitance 0.15 [get_ports {out_weight[6]}]
set_max_capacitance 0.15 [get_ports {out_weight[5]}]
set_max_capacitance 0.15 [get_ports {out_weight[4]}]
set_max_capacitance 0.15 [get_ports {out_weight[3]}]
set_max_capacitance 0.15 [get_ports {out_weight[2]}]
set_max_capacitance 0.15 [get_ports {out_weight[1]}]
set_max_capacitance 0.15 [get_ports {out_weight[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports {Q[31]}]
set_max_fanout 10 [get_ports {Q[30]}]
set_max_fanout 10 [get_ports {Q[29]}]
set_max_fanout 10 [get_ports {Q[28]}]
set_max_fanout 10 [get_ports {Q[27]}]
set_max_fanout 10 [get_ports {Q[26]}]
set_max_fanout 10 [get_ports {Q[25]}]
set_max_fanout 10 [get_ports {Q[24]}]
set_max_fanout 10 [get_ports {Q[23]}]
set_max_fanout 10 [get_ports {Q[22]}]
set_max_fanout 10 [get_ports {Q[21]}]
set_max_fanout 10 [get_ports {Q[20]}]
set_max_fanout 10 [get_ports {Q[19]}]
set_max_fanout 10 [get_ports {Q[18]}]
set_max_fanout 10 [get_ports {Q[17]}]
set_max_fanout 10 [get_ports {Q[16]}]
set_max_fanout 10 [get_ports {Q[15]}]
set_max_fanout 10 [get_ports {Q[14]}]
set_max_fanout 10 [get_ports {Q[13]}]
set_max_fanout 10 [get_ports {Q[12]}]
set_max_fanout 10 [get_ports {Q[11]}]
set_max_fanout 10 [get_ports {Q[10]}]
set_max_fanout 10 [get_ports {Q[9]}]
set_max_fanout 10 [get_ports {Q[8]}]
set_max_fanout 10 [get_ports {Q[7]}]
set_max_fanout 10 [get_ports {Q[6]}]
set_max_fanout 10 [get_ports {Q[5]}]
set_max_fanout 10 [get_ports {Q[4]}]
set_max_fanout 10 [get_ports {Q[3]}]
set_max_fanout 10 [get_ports {Q[2]}]
set_max_fanout 10 [get_ports {Q[1]}]
set_max_fanout 10 [get_ports {Q[0]}]
set_max_fanout 10 [get_ports {K[31]}]
set_max_fanout 10 [get_ports {K[30]}]
set_max_fanout 10 [get_ports {K[29]}]
set_max_fanout 10 [get_ports {K[28]}]
set_max_fanout 10 [get_ports {K[27]}]
set_max_fanout 10 [get_ports {K[26]}]
set_max_fanout 10 [get_ports {K[25]}]
set_max_fanout 10 [get_ports {K[24]}]
set_max_fanout 10 [get_ports {K[23]}]
set_max_fanout 10 [get_ports {K[22]}]
set_max_fanout 10 [get_ports {K[21]}]
set_max_fanout 10 [get_ports {K[20]}]
set_max_fanout 10 [get_ports {K[19]}]
set_max_fanout 10 [get_ports {K[18]}]
set_max_fanout 10 [get_ports {K[17]}]
set_max_fanout 10 [get_ports {K[16]}]
set_max_fanout 10 [get_ports {K[15]}]
set_max_fanout 10 [get_ports {K[14]}]
set_max_fanout 10 [get_ports {K[13]}]
set_max_fanout 10 [get_ports {K[12]}]
set_max_fanout 10 [get_ports {K[11]}]
set_max_fanout 10 [get_ports {K[10]}]
set_max_fanout 10 [get_ports {K[9]}]
set_max_fanout 10 [get_ports {K[8]}]
set_max_fanout 10 [get_ports {K[7]}]
set_max_fanout 10 [get_ports {K[6]}]
set_max_fanout 10 [get_ports {K[5]}]
set_max_fanout 10 [get_ports {K[4]}]
set_max_fanout 10 [get_ports {K[3]}]
set_max_fanout 10 [get_ports {K[2]}]
set_max_fanout 10 [get_ports {K[1]}]
set_max_fanout 10 [get_ports {K[0]}]
set_max_fanout 10 [get_ports {V[31]}]
set_max_fanout 10 [get_ports {V[30]}]
set_max_fanout 10 [get_ports {V[29]}]
set_max_fanout 10 [get_ports {V[28]}]
set_max_fanout 10 [get_ports {V[27]}]
set_max_fanout 10 [get_ports {V[26]}]
set_max_fanout 10 [get_ports {V[25]}]
set_max_fanout 10 [get_ports {V[24]}]
set_max_fanout 10 [get_ports {V[23]}]
set_max_fanout 10 [get_ports {V[22]}]
set_max_fanout 10 [get_ports {V[21]}]
set_max_fanout 10 [get_ports {V[20]}]
set_max_fanout 10 [get_ports {V[19]}]
set_max_fanout 10 [get_ports {V[18]}]
set_max_fanout 10 [get_ports {V[17]}]
set_max_fanout 10 [get_ports {V[16]}]
set_max_fanout 10 [get_ports {V[15]}]
set_max_fanout 10 [get_ports {V[14]}]
set_max_fanout 10 [get_ports {V[13]}]
set_max_fanout 10 [get_ports {V[12]}]
set_max_fanout 10 [get_ports {V[11]}]
set_max_fanout 10 [get_ports {V[10]}]
set_max_fanout 10 [get_ports {V[9]}]
set_max_fanout 10 [get_ports {V[8]}]
set_max_fanout 10 [get_ports {V[7]}]
set_max_fanout 10 [get_ports {V[6]}]
set_max_fanout 10 [get_ports {V[5]}]
set_max_fanout 10 [get_ports {V[4]}]
set_max_fanout 10 [get_ports {V[3]}]
set_max_fanout 10 [get_ports {V[2]}]
set_max_fanout 10 [get_ports {V[1]}]
set_max_fanout 10 [get_ports {V[0]}]
set_max_fanout 10 [get_ports {out_weight[31]}]
set_max_fanout 10 [get_ports {out_weight[30]}]
set_max_fanout 10 [get_ports {out_weight[29]}]
set_max_fanout 10 [get_ports {out_weight[28]}]
set_max_fanout 10 [get_ports {out_weight[27]}]
set_max_fanout 10 [get_ports {out_weight[26]}]
set_max_fanout 10 [get_ports {out_weight[25]}]
set_max_fanout 10 [get_ports {out_weight[24]}]
set_max_fanout 10 [get_ports {out_weight[23]}]
set_max_fanout 10 [get_ports {out_weight[22]}]
set_max_fanout 10 [get_ports {out_weight[21]}]
set_max_fanout 10 [get_ports {out_weight[20]}]
set_max_fanout 10 [get_ports {out_weight[19]}]
set_max_fanout 10 [get_ports {out_weight[18]}]
set_max_fanout 10 [get_ports {out_weight[17]}]
set_max_fanout 10 [get_ports {out_weight[16]}]
set_max_fanout 10 [get_ports {out_weight[15]}]
set_max_fanout 10 [get_ports {out_weight[14]}]
set_max_fanout 10 [get_ports {out_weight[13]}]
set_max_fanout 10 [get_ports {out_weight[12]}]
set_max_fanout 10 [get_ports {out_weight[11]}]
set_max_fanout 10 [get_ports {out_weight[10]}]
set_max_fanout 10 [get_ports {out_weight[9]}]
set_max_fanout 10 [get_ports {out_weight[8]}]
set_max_fanout 10 [get_ports {out_weight[7]}]
set_max_fanout 10 [get_ports {out_weight[6]}]
set_max_fanout 10 [get_ports {out_weight[5]}]
set_max_fanout 10 [get_ports {out_weight[4]}]
set_max_fanout 10 [get_ports {out_weight[3]}]
set_max_fanout 10 [get_ports {out_weight[2]}]
set_max_fanout 10 [get_ports {out_weight[1]}]
set_max_fanout 10 [get_ports {out_weight[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports {Q[31]}]
set_max_transition 3 [get_ports {Q[30]}]
set_max_transition 3 [get_ports {Q[29]}]
set_max_transition 3 [get_ports {Q[28]}]
set_max_transition 3 [get_ports {Q[27]}]
set_max_transition 3 [get_ports {Q[26]}]
set_max_transition 3 [get_ports {Q[25]}]
set_max_transition 3 [get_ports {Q[24]}]
set_max_transition 3 [get_ports {Q[23]}]
set_max_transition 3 [get_ports {Q[22]}]
set_max_transition 3 [get_ports {Q[21]}]
set_max_transition 3 [get_ports {Q[20]}]
set_max_transition 3 [get_ports {Q[19]}]
set_max_transition 3 [get_ports {Q[18]}]
set_max_transition 3 [get_ports {Q[17]}]
set_max_transition 3 [get_ports {Q[16]}]
set_max_transition 3 [get_ports {Q[15]}]
set_max_transition 3 [get_ports {Q[14]}]
set_max_transition 3 [get_ports {Q[13]}]
set_max_transition 3 [get_ports {Q[12]}]
set_max_transition 3 [get_ports {Q[11]}]
set_max_transition 3 [get_ports {Q[10]}]
set_max_transition 3 [get_ports {Q[9]}]
set_max_transition 3 [get_ports {Q[8]}]
set_max_transition 3 [get_ports {Q[7]}]
set_max_transition 3 [get_ports {Q[6]}]
set_max_transition 3 [get_ports {Q[5]}]
set_max_transition 3 [get_ports {Q[4]}]
set_max_transition 3 [get_ports {Q[3]}]
set_max_transition 3 [get_ports {Q[2]}]
set_max_transition 3 [get_ports {Q[1]}]
set_max_transition 3 [get_ports {Q[0]}]
set_max_transition 3 [get_ports {K[31]}]
set_max_transition 3 [get_ports {K[30]}]
set_max_transition 3 [get_ports {K[29]}]
set_max_transition 3 [get_ports {K[28]}]
set_max_transition 3 [get_ports {K[27]}]
set_max_transition 3 [get_ports {K[26]}]
set_max_transition 3 [get_ports {K[25]}]
set_max_transition 3 [get_ports {K[24]}]
set_max_transition 3 [get_ports {K[23]}]
set_max_transition 3 [get_ports {K[22]}]
set_max_transition 3 [get_ports {K[21]}]
set_max_transition 3 [get_ports {K[20]}]
set_max_transition 3 [get_ports {K[19]}]
set_max_transition 3 [get_ports {K[18]}]
set_max_transition 3 [get_ports {K[17]}]
set_max_transition 3 [get_ports {K[16]}]
set_max_transition 3 [get_ports {K[15]}]
set_max_transition 3 [get_ports {K[14]}]
set_max_transition 3 [get_ports {K[13]}]
set_max_transition 3 [get_ports {K[12]}]
set_max_transition 3 [get_ports {K[11]}]
set_max_transition 3 [get_ports {K[10]}]
set_max_transition 3 [get_ports {K[9]}]
set_max_transition 3 [get_ports {K[8]}]
set_max_transition 3 [get_ports {K[7]}]
set_max_transition 3 [get_ports {K[6]}]
set_max_transition 3 [get_ports {K[5]}]
set_max_transition 3 [get_ports {K[4]}]
set_max_transition 3 [get_ports {K[3]}]
set_max_transition 3 [get_ports {K[2]}]
set_max_transition 3 [get_ports {K[1]}]
set_max_transition 3 [get_ports {K[0]}]
set_max_transition 3 [get_ports {V[31]}]
set_max_transition 3 [get_ports {V[30]}]
set_max_transition 3 [get_ports {V[29]}]
set_max_transition 3 [get_ports {V[28]}]
set_max_transition 3 [get_ports {V[27]}]
set_max_transition 3 [get_ports {V[26]}]
set_max_transition 3 [get_ports {V[25]}]
set_max_transition 3 [get_ports {V[24]}]
set_max_transition 3 [get_ports {V[23]}]
set_max_transition 3 [get_ports {V[22]}]
set_max_transition 3 [get_ports {V[21]}]
set_max_transition 3 [get_ports {V[20]}]
set_max_transition 3 [get_ports {V[19]}]
set_max_transition 3 [get_ports {V[18]}]
set_max_transition 3 [get_ports {V[17]}]
set_max_transition 3 [get_ports {V[16]}]
set_max_transition 3 [get_ports {V[15]}]
set_max_transition 3 [get_ports {V[14]}]
set_max_transition 3 [get_ports {V[13]}]
set_max_transition 3 [get_ports {V[12]}]
set_max_transition 3 [get_ports {V[11]}]
set_max_transition 3 [get_ports {V[10]}]
set_max_transition 3 [get_ports {V[9]}]
set_max_transition 3 [get_ports {V[8]}]
set_max_transition 3 [get_ports {V[7]}]
set_max_transition 3 [get_ports {V[6]}]
set_max_transition 3 [get_ports {V[5]}]
set_max_transition 3 [get_ports {V[4]}]
set_max_transition 3 [get_ports {V[3]}]
set_max_transition 3 [get_ports {V[2]}]
set_max_transition 3 [get_ports {V[1]}]
set_max_transition 3 [get_ports {V[0]}]
set_max_transition 3 [get_ports {out_weight[31]}]
set_max_transition 3 [get_ports {out_weight[30]}]
set_max_transition 3 [get_ports {out_weight[29]}]
set_max_transition 3 [get_ports {out_weight[28]}]
set_max_transition 3 [get_ports {out_weight[27]}]
set_max_transition 3 [get_ports {out_weight[26]}]
set_max_transition 3 [get_ports {out_weight[25]}]
set_max_transition 3 [get_ports {out_weight[24]}]
set_max_transition 3 [get_ports {out_weight[23]}]
set_max_transition 3 [get_ports {out_weight[22]}]
set_max_transition 3 [get_ports {out_weight[21]}]
set_max_transition 3 [get_ports {out_weight[20]}]
set_max_transition 3 [get_ports {out_weight[19]}]
set_max_transition 3 [get_ports {out_weight[18]}]
set_max_transition 3 [get_ports {out_weight[17]}]
set_max_transition 3 [get_ports {out_weight[16]}]
set_max_transition 3 [get_ports {out_weight[15]}]
set_max_transition 3 [get_ports {out_weight[14]}]
set_max_transition 3 [get_ports {out_weight[13]}]
set_max_transition 3 [get_ports {out_weight[12]}]
set_max_transition 3 [get_ports {out_weight[11]}]
set_max_transition 3 [get_ports {out_weight[10]}]
set_max_transition 3 [get_ports {out_weight[9]}]
set_max_transition 3 [get_ports {out_weight[8]}]
set_max_transition 3 [get_ports {out_weight[7]}]
set_max_transition 3 [get_ports {out_weight[6]}]
set_max_transition 3 [get_ports {out_weight[5]}]
set_max_transition 3 [get_ports {out_weight[4]}]
set_max_transition 3 [get_ports {out_weight[3]}]
set_max_transition 3 [get_ports {out_weight[2]}]
set_max_transition 3 [get_ports {out_weight[1]}]
set_max_transition 3 [get_ports {out_weight[0]}]
create_clock [get_ports clk]  -period 50  -waveform {0 25}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 25  [get_ports in_valid]
set_input_delay -clock clk  -min 0  [get_ports in_valid]
set_input_delay -clock clk  -max 25  [get_ports {Q[31]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[31]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[30]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[30]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[29]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[29]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[28]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[28]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[27]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[27]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[26]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[26]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[25]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[25]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[24]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[24]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[23]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[23]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[22]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[22]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[21]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[21]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[20]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[20]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[19]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[19]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[18]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[18]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[17]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[17]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[16]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[16]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[15]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[15]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[14]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[14]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[13]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[13]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[12]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[12]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[11]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[11]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[10]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[10]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[9]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[9]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[8]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[8]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[7]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[7]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[6]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[6]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[5]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[5]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[4]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[4]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[3]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[3]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[2]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[2]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[1]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[1]}]
set_input_delay -clock clk  -max 25  [get_ports {Q[0]}]
set_input_delay -clock clk  -min 0  [get_ports {Q[0]}]
set_input_delay -clock clk  -max 25  [get_ports {K[31]}]
set_input_delay -clock clk  -min 0  [get_ports {K[31]}]
set_input_delay -clock clk  -max 25  [get_ports {K[30]}]
set_input_delay -clock clk  -min 0  [get_ports {K[30]}]
set_input_delay -clock clk  -max 25  [get_ports {K[29]}]
set_input_delay -clock clk  -min 0  [get_ports {K[29]}]
set_input_delay -clock clk  -max 25  [get_ports {K[28]}]
set_input_delay -clock clk  -min 0  [get_ports {K[28]}]
set_input_delay -clock clk  -max 25  [get_ports {K[27]}]
set_input_delay -clock clk  -min 0  [get_ports {K[27]}]
set_input_delay -clock clk  -max 25  [get_ports {K[26]}]
set_input_delay -clock clk  -min 0  [get_ports {K[26]}]
set_input_delay -clock clk  -max 25  [get_ports {K[25]}]
set_input_delay -clock clk  -min 0  [get_ports {K[25]}]
set_input_delay -clock clk  -max 25  [get_ports {K[24]}]
set_input_delay -clock clk  -min 0  [get_ports {K[24]}]
set_input_delay -clock clk  -max 25  [get_ports {K[23]}]
set_input_delay -clock clk  -min 0  [get_ports {K[23]}]
set_input_delay -clock clk  -max 25  [get_ports {K[22]}]
set_input_delay -clock clk  -min 0  [get_ports {K[22]}]
set_input_delay -clock clk  -max 25  [get_ports {K[21]}]
set_input_delay -clock clk  -min 0  [get_ports {K[21]}]
set_input_delay -clock clk  -max 25  [get_ports {K[20]}]
set_input_delay -clock clk  -min 0  [get_ports {K[20]}]
set_input_delay -clock clk  -max 25  [get_ports {K[19]}]
set_input_delay -clock clk  -min 0  [get_ports {K[19]}]
set_input_delay -clock clk  -max 25  [get_ports {K[18]}]
set_input_delay -clock clk  -min 0  [get_ports {K[18]}]
set_input_delay -clock clk  -max 25  [get_ports {K[17]}]
set_input_delay -clock clk  -min 0  [get_ports {K[17]}]
set_input_delay -clock clk  -max 25  [get_ports {K[16]}]
set_input_delay -clock clk  -min 0  [get_ports {K[16]}]
set_input_delay -clock clk  -max 25  [get_ports {K[15]}]
set_input_delay -clock clk  -min 0  [get_ports {K[15]}]
set_input_delay -clock clk  -max 25  [get_ports {K[14]}]
set_input_delay -clock clk  -min 0  [get_ports {K[14]}]
set_input_delay -clock clk  -max 25  [get_ports {K[13]}]
set_input_delay -clock clk  -min 0  [get_ports {K[13]}]
set_input_delay -clock clk  -max 25  [get_ports {K[12]}]
set_input_delay -clock clk  -min 0  [get_ports {K[12]}]
set_input_delay -clock clk  -max 25  [get_ports {K[11]}]
set_input_delay -clock clk  -min 0  [get_ports {K[11]}]
set_input_delay -clock clk  -max 25  [get_ports {K[10]}]
set_input_delay -clock clk  -min 0  [get_ports {K[10]}]
set_input_delay -clock clk  -max 25  [get_ports {K[9]}]
set_input_delay -clock clk  -min 0  [get_ports {K[9]}]
set_input_delay -clock clk  -max 25  [get_ports {K[8]}]
set_input_delay -clock clk  -min 0  [get_ports {K[8]}]
set_input_delay -clock clk  -max 25  [get_ports {K[7]}]
set_input_delay -clock clk  -min 0  [get_ports {K[7]}]
set_input_delay -clock clk  -max 25  [get_ports {K[6]}]
set_input_delay -clock clk  -min 0  [get_ports {K[6]}]
set_input_delay -clock clk  -max 25  [get_ports {K[5]}]
set_input_delay -clock clk  -min 0  [get_ports {K[5]}]
set_input_delay -clock clk  -max 25  [get_ports {K[4]}]
set_input_delay -clock clk  -min 0  [get_ports {K[4]}]
set_input_delay -clock clk  -max 25  [get_ports {K[3]}]
set_input_delay -clock clk  -min 0  [get_ports {K[3]}]
set_input_delay -clock clk  -max 25  [get_ports {K[2]}]
set_input_delay -clock clk  -min 0  [get_ports {K[2]}]
set_input_delay -clock clk  -max 25  [get_ports {K[1]}]
set_input_delay -clock clk  -min 0  [get_ports {K[1]}]
set_input_delay -clock clk  -max 25  [get_ports {K[0]}]
set_input_delay -clock clk  -min 0  [get_ports {K[0]}]
set_input_delay -clock clk  -max 25  [get_ports {V[31]}]
set_input_delay -clock clk  -min 0  [get_ports {V[31]}]
set_input_delay -clock clk  -max 25  [get_ports {V[30]}]
set_input_delay -clock clk  -min 0  [get_ports {V[30]}]
set_input_delay -clock clk  -max 25  [get_ports {V[29]}]
set_input_delay -clock clk  -min 0  [get_ports {V[29]}]
set_input_delay -clock clk  -max 25  [get_ports {V[28]}]
set_input_delay -clock clk  -min 0  [get_ports {V[28]}]
set_input_delay -clock clk  -max 25  [get_ports {V[27]}]
set_input_delay -clock clk  -min 0  [get_ports {V[27]}]
set_input_delay -clock clk  -max 25  [get_ports {V[26]}]
set_input_delay -clock clk  -min 0  [get_ports {V[26]}]
set_input_delay -clock clk  -max 25  [get_ports {V[25]}]
set_input_delay -clock clk  -min 0  [get_ports {V[25]}]
set_input_delay -clock clk  -max 25  [get_ports {V[24]}]
set_input_delay -clock clk  -min 0  [get_ports {V[24]}]
set_input_delay -clock clk  -max 25  [get_ports {V[23]}]
set_input_delay -clock clk  -min 0  [get_ports {V[23]}]
set_input_delay -clock clk  -max 25  [get_ports {V[22]}]
set_input_delay -clock clk  -min 0  [get_ports {V[22]}]
set_input_delay -clock clk  -max 25  [get_ports {V[21]}]
set_input_delay -clock clk  -min 0  [get_ports {V[21]}]
set_input_delay -clock clk  -max 25  [get_ports {V[20]}]
set_input_delay -clock clk  -min 0  [get_ports {V[20]}]
set_input_delay -clock clk  -max 25  [get_ports {V[19]}]
set_input_delay -clock clk  -min 0  [get_ports {V[19]}]
set_input_delay -clock clk  -max 25  [get_ports {V[18]}]
set_input_delay -clock clk  -min 0  [get_ports {V[18]}]
set_input_delay -clock clk  -max 25  [get_ports {V[17]}]
set_input_delay -clock clk  -min 0  [get_ports {V[17]}]
set_input_delay -clock clk  -max 25  [get_ports {V[16]}]
set_input_delay -clock clk  -min 0  [get_ports {V[16]}]
set_input_delay -clock clk  -max 25  [get_ports {V[15]}]
set_input_delay -clock clk  -min 0  [get_ports {V[15]}]
set_input_delay -clock clk  -max 25  [get_ports {V[14]}]
set_input_delay -clock clk  -min 0  [get_ports {V[14]}]
set_input_delay -clock clk  -max 25  [get_ports {V[13]}]
set_input_delay -clock clk  -min 0  [get_ports {V[13]}]
set_input_delay -clock clk  -max 25  [get_ports {V[12]}]
set_input_delay -clock clk  -min 0  [get_ports {V[12]}]
set_input_delay -clock clk  -max 25  [get_ports {V[11]}]
set_input_delay -clock clk  -min 0  [get_ports {V[11]}]
set_input_delay -clock clk  -max 25  [get_ports {V[10]}]
set_input_delay -clock clk  -min 0  [get_ports {V[10]}]
set_input_delay -clock clk  -max 25  [get_ports {V[9]}]
set_input_delay -clock clk  -min 0  [get_ports {V[9]}]
set_input_delay -clock clk  -max 25  [get_ports {V[8]}]
set_input_delay -clock clk  -min 0  [get_ports {V[8]}]
set_input_delay -clock clk  -max 25  [get_ports {V[7]}]
set_input_delay -clock clk  -min 0  [get_ports {V[7]}]
set_input_delay -clock clk  -max 25  [get_ports {V[6]}]
set_input_delay -clock clk  -min 0  [get_ports {V[6]}]
set_input_delay -clock clk  -max 25  [get_ports {V[5]}]
set_input_delay -clock clk  -min 0  [get_ports {V[5]}]
set_input_delay -clock clk  -max 25  [get_ports {V[4]}]
set_input_delay -clock clk  -min 0  [get_ports {V[4]}]
set_input_delay -clock clk  -max 25  [get_ports {V[3]}]
set_input_delay -clock clk  -min 0  [get_ports {V[3]}]
set_input_delay -clock clk  -max 25  [get_ports {V[2]}]
set_input_delay -clock clk  -min 0  [get_ports {V[2]}]
set_input_delay -clock clk  -max 25  [get_ports {V[1]}]
set_input_delay -clock clk  -min 0  [get_ports {V[1]}]
set_input_delay -clock clk  -max 25  [get_ports {V[0]}]
set_input_delay -clock clk  -min 0  [get_ports {V[0]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[31]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[31]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[30]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[30]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[29]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[29]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[28]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[28]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[27]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[27]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[26]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[26]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[25]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[25]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[24]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[24]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[23]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[23]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[22]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[22]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[21]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[21]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[20]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[20]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[19]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[19]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[18]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[18]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[17]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[17]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[16]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[16]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[15]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[15]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[14]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[14]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[13]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[13]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[12]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[12]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[11]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[11]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[10]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[10]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[9]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[9]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[8]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[8]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[7]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[7]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[6]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[6]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[5]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[5]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[4]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[4]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[3]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[3]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[2]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[2]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[1]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[1]}]
set_input_delay -clock clk  -max 25  [get_ports {out_weight[0]}]
set_input_delay -clock clk  -min 0  [get_ports {out_weight[0]}]
set_output_delay -clock clk  -max 25  [get_ports out_valid]
set_output_delay -clock clk  -min 0  [get_ports out_valid]
set_output_delay -clock clk  -max 25  [get_ports {out[31]}]
set_output_delay -clock clk  -min 0  [get_ports {out[31]}]
set_output_delay -clock clk  -max 25  [get_ports {out[30]}]
set_output_delay -clock clk  -min 0  [get_ports {out[30]}]
set_output_delay -clock clk  -max 25  [get_ports {out[29]}]
set_output_delay -clock clk  -min 0  [get_ports {out[29]}]
set_output_delay -clock clk  -max 25  [get_ports {out[28]}]
set_output_delay -clock clk  -min 0  [get_ports {out[28]}]
set_output_delay -clock clk  -max 25  [get_ports {out[27]}]
set_output_delay -clock clk  -min 0  [get_ports {out[27]}]
set_output_delay -clock clk  -max 25  [get_ports {out[26]}]
set_output_delay -clock clk  -min 0  [get_ports {out[26]}]
set_output_delay -clock clk  -max 25  [get_ports {out[25]}]
set_output_delay -clock clk  -min 0  [get_ports {out[25]}]
set_output_delay -clock clk  -max 25  [get_ports {out[24]}]
set_output_delay -clock clk  -min 0  [get_ports {out[24]}]
set_output_delay -clock clk  -max 25  [get_ports {out[23]}]
set_output_delay -clock clk  -min 0  [get_ports {out[23]}]
set_output_delay -clock clk  -max 25  [get_ports {out[22]}]
set_output_delay -clock clk  -min 0  [get_ports {out[22]}]
set_output_delay -clock clk  -max 25  [get_ports {out[21]}]
set_output_delay -clock clk  -min 0  [get_ports {out[21]}]
set_output_delay -clock clk  -max 25  [get_ports {out[20]}]
set_output_delay -clock clk  -min 0  [get_ports {out[20]}]
set_output_delay -clock clk  -max 25  [get_ports {out[19]}]
set_output_delay -clock clk  -min 0  [get_ports {out[19]}]
set_output_delay -clock clk  -max 25  [get_ports {out[18]}]
set_output_delay -clock clk  -min 0  [get_ports {out[18]}]
set_output_delay -clock clk  -max 25  [get_ports {out[17]}]
set_output_delay -clock clk  -min 0  [get_ports {out[17]}]
set_output_delay -clock clk  -max 25  [get_ports {out[16]}]
set_output_delay -clock clk  -min 0  [get_ports {out[16]}]
set_output_delay -clock clk  -max 25  [get_ports {out[15]}]
set_output_delay -clock clk  -min 0  [get_ports {out[15]}]
set_output_delay -clock clk  -max 25  [get_ports {out[14]}]
set_output_delay -clock clk  -min 0  [get_ports {out[14]}]
set_output_delay -clock clk  -max 25  [get_ports {out[13]}]
set_output_delay -clock clk  -min 0  [get_ports {out[13]}]
set_output_delay -clock clk  -max 25  [get_ports {out[12]}]
set_output_delay -clock clk  -min 0  [get_ports {out[12]}]
set_output_delay -clock clk  -max 25  [get_ports {out[11]}]
set_output_delay -clock clk  -min 0  [get_ports {out[11]}]
set_output_delay -clock clk  -max 25  [get_ports {out[10]}]
set_output_delay -clock clk  -min 0  [get_ports {out[10]}]
set_output_delay -clock clk  -max 25  [get_ports {out[9]}]
set_output_delay -clock clk  -min 0  [get_ports {out[9]}]
set_output_delay -clock clk  -max 25  [get_ports {out[8]}]
set_output_delay -clock clk  -min 0  [get_ports {out[8]}]
set_output_delay -clock clk  -max 25  [get_ports {out[7]}]
set_output_delay -clock clk  -min 0  [get_ports {out[7]}]
set_output_delay -clock clk  -max 25  [get_ports {out[6]}]
set_output_delay -clock clk  -min 0  [get_ports {out[6]}]
set_output_delay -clock clk  -max 25  [get_ports {out[5]}]
set_output_delay -clock clk  -min 0  [get_ports {out[5]}]
set_output_delay -clock clk  -max 25  [get_ports {out[4]}]
set_output_delay -clock clk  -min 0  [get_ports {out[4]}]
set_output_delay -clock clk  -max 25  [get_ports {out[3]}]
set_output_delay -clock clk  -min 0  [get_ports {out[3]}]
set_output_delay -clock clk  -max 25  [get_ports {out[2]}]
set_output_delay -clock clk  -min 0  [get_ports {out[2]}]
set_output_delay -clock clk  -max 25  [get_ports {out[1]}]
set_output_delay -clock clk  -min 0  [get_ports {out[1]}]
set_output_delay -clock clk  -max 25  [get_ports {out[0]}]
set_output_delay -clock clk  -min 0  [get_ports {out[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {Q[31]}]
set_input_transition -min 0.5  [get_ports {Q[31]}]
set_input_transition -max 0.5  [get_ports {Q[30]}]
set_input_transition -min 0.5  [get_ports {Q[30]}]
set_input_transition -max 0.5  [get_ports {Q[29]}]
set_input_transition -min 0.5  [get_ports {Q[29]}]
set_input_transition -max 0.5  [get_ports {Q[28]}]
set_input_transition -min 0.5  [get_ports {Q[28]}]
set_input_transition -max 0.5  [get_ports {Q[27]}]
set_input_transition -min 0.5  [get_ports {Q[27]}]
set_input_transition -max 0.5  [get_ports {Q[26]}]
set_input_transition -min 0.5  [get_ports {Q[26]}]
set_input_transition -max 0.5  [get_ports {Q[25]}]
set_input_transition -min 0.5  [get_ports {Q[25]}]
set_input_transition -max 0.5  [get_ports {Q[24]}]
set_input_transition -min 0.5  [get_ports {Q[24]}]
set_input_transition -max 0.5  [get_ports {Q[23]}]
set_input_transition -min 0.5  [get_ports {Q[23]}]
set_input_transition -max 0.5  [get_ports {Q[22]}]
set_input_transition -min 0.5  [get_ports {Q[22]}]
set_input_transition -max 0.5  [get_ports {Q[21]}]
set_input_transition -min 0.5  [get_ports {Q[21]}]
set_input_transition -max 0.5  [get_ports {Q[20]}]
set_input_transition -min 0.5  [get_ports {Q[20]}]
set_input_transition -max 0.5  [get_ports {Q[19]}]
set_input_transition -min 0.5  [get_ports {Q[19]}]
set_input_transition -max 0.5  [get_ports {Q[18]}]
set_input_transition -min 0.5  [get_ports {Q[18]}]
set_input_transition -max 0.5  [get_ports {Q[17]}]
set_input_transition -min 0.5  [get_ports {Q[17]}]
set_input_transition -max 0.5  [get_ports {Q[16]}]
set_input_transition -min 0.5  [get_ports {Q[16]}]
set_input_transition -max 0.5  [get_ports {Q[15]}]
set_input_transition -min 0.5  [get_ports {Q[15]}]
set_input_transition -max 0.5  [get_ports {Q[14]}]
set_input_transition -min 0.5  [get_ports {Q[14]}]
set_input_transition -max 0.5  [get_ports {Q[13]}]
set_input_transition -min 0.5  [get_ports {Q[13]}]
set_input_transition -max 0.5  [get_ports {Q[12]}]
set_input_transition -min 0.5  [get_ports {Q[12]}]
set_input_transition -max 0.5  [get_ports {Q[11]}]
set_input_transition -min 0.5  [get_ports {Q[11]}]
set_input_transition -max 0.5  [get_ports {Q[10]}]
set_input_transition -min 0.5  [get_ports {Q[10]}]
set_input_transition -max 0.5  [get_ports {Q[9]}]
set_input_transition -min 0.5  [get_ports {Q[9]}]
set_input_transition -max 0.5  [get_ports {Q[8]}]
set_input_transition -min 0.5  [get_ports {Q[8]}]
set_input_transition -max 0.5  [get_ports {Q[7]}]
set_input_transition -min 0.5  [get_ports {Q[7]}]
set_input_transition -max 0.5  [get_ports {Q[6]}]
set_input_transition -min 0.5  [get_ports {Q[6]}]
set_input_transition -max 0.5  [get_ports {Q[5]}]
set_input_transition -min 0.5  [get_ports {Q[5]}]
set_input_transition -max 0.5  [get_ports {Q[4]}]
set_input_transition -min 0.5  [get_ports {Q[4]}]
set_input_transition -max 0.5  [get_ports {Q[3]}]
set_input_transition -min 0.5  [get_ports {Q[3]}]
set_input_transition -max 0.5  [get_ports {Q[2]}]
set_input_transition -min 0.5  [get_ports {Q[2]}]
set_input_transition -max 0.5  [get_ports {Q[1]}]
set_input_transition -min 0.5  [get_ports {Q[1]}]
set_input_transition -max 0.5  [get_ports {Q[0]}]
set_input_transition -min 0.5  [get_ports {Q[0]}]
set_input_transition -max 0.5  [get_ports {K[31]}]
set_input_transition -min 0.5  [get_ports {K[31]}]
set_input_transition -max 0.5  [get_ports {K[30]}]
set_input_transition -min 0.5  [get_ports {K[30]}]
set_input_transition -max 0.5  [get_ports {K[29]}]
set_input_transition -min 0.5  [get_ports {K[29]}]
set_input_transition -max 0.5  [get_ports {K[28]}]
set_input_transition -min 0.5  [get_ports {K[28]}]
set_input_transition -max 0.5  [get_ports {K[27]}]
set_input_transition -min 0.5  [get_ports {K[27]}]
set_input_transition -max 0.5  [get_ports {K[26]}]
set_input_transition -min 0.5  [get_ports {K[26]}]
set_input_transition -max 0.5  [get_ports {K[25]}]
set_input_transition -min 0.5  [get_ports {K[25]}]
set_input_transition -max 0.5  [get_ports {K[24]}]
set_input_transition -min 0.5  [get_ports {K[24]}]
set_input_transition -max 0.5  [get_ports {K[23]}]
set_input_transition -min 0.5  [get_ports {K[23]}]
set_input_transition -max 0.5  [get_ports {K[22]}]
set_input_transition -min 0.5  [get_ports {K[22]}]
set_input_transition -max 0.5  [get_ports {K[21]}]
set_input_transition -min 0.5  [get_ports {K[21]}]
set_input_transition -max 0.5  [get_ports {K[20]}]
set_input_transition -min 0.5  [get_ports {K[20]}]
set_input_transition -max 0.5  [get_ports {K[19]}]
set_input_transition -min 0.5  [get_ports {K[19]}]
set_input_transition -max 0.5  [get_ports {K[18]}]
set_input_transition -min 0.5  [get_ports {K[18]}]
set_input_transition -max 0.5  [get_ports {K[17]}]
set_input_transition -min 0.5  [get_ports {K[17]}]
set_input_transition -max 0.5  [get_ports {K[16]}]
set_input_transition -min 0.5  [get_ports {K[16]}]
set_input_transition -max 0.5  [get_ports {K[15]}]
set_input_transition -min 0.5  [get_ports {K[15]}]
set_input_transition -max 0.5  [get_ports {K[14]}]
set_input_transition -min 0.5  [get_ports {K[14]}]
set_input_transition -max 0.5  [get_ports {K[13]}]
set_input_transition -min 0.5  [get_ports {K[13]}]
set_input_transition -max 0.5  [get_ports {K[12]}]
set_input_transition -min 0.5  [get_ports {K[12]}]
set_input_transition -max 0.5  [get_ports {K[11]}]
set_input_transition -min 0.5  [get_ports {K[11]}]
set_input_transition -max 0.5  [get_ports {K[10]}]
set_input_transition -min 0.5  [get_ports {K[10]}]
set_input_transition -max 0.5  [get_ports {K[9]}]
set_input_transition -min 0.5  [get_ports {K[9]}]
set_input_transition -max 0.5  [get_ports {K[8]}]
set_input_transition -min 0.5  [get_ports {K[8]}]
set_input_transition -max 0.5  [get_ports {K[7]}]
set_input_transition -min 0.5  [get_ports {K[7]}]
set_input_transition -max 0.5  [get_ports {K[6]}]
set_input_transition -min 0.5  [get_ports {K[6]}]
set_input_transition -max 0.5  [get_ports {K[5]}]
set_input_transition -min 0.5  [get_ports {K[5]}]
set_input_transition -max 0.5  [get_ports {K[4]}]
set_input_transition -min 0.5  [get_ports {K[4]}]
set_input_transition -max 0.5  [get_ports {K[3]}]
set_input_transition -min 0.5  [get_ports {K[3]}]
set_input_transition -max 0.5  [get_ports {K[2]}]
set_input_transition -min 0.5  [get_ports {K[2]}]
set_input_transition -max 0.5  [get_ports {K[1]}]
set_input_transition -min 0.5  [get_ports {K[1]}]
set_input_transition -max 0.5  [get_ports {K[0]}]
set_input_transition -min 0.5  [get_ports {K[0]}]
set_input_transition -max 0.5  [get_ports {V[31]}]
set_input_transition -min 0.5  [get_ports {V[31]}]
set_input_transition -max 0.5  [get_ports {V[30]}]
set_input_transition -min 0.5  [get_ports {V[30]}]
set_input_transition -max 0.5  [get_ports {V[29]}]
set_input_transition -min 0.5  [get_ports {V[29]}]
set_input_transition -max 0.5  [get_ports {V[28]}]
set_input_transition -min 0.5  [get_ports {V[28]}]
set_input_transition -max 0.5  [get_ports {V[27]}]
set_input_transition -min 0.5  [get_ports {V[27]}]
set_input_transition -max 0.5  [get_ports {V[26]}]
set_input_transition -min 0.5  [get_ports {V[26]}]
set_input_transition -max 0.5  [get_ports {V[25]}]
set_input_transition -min 0.5  [get_ports {V[25]}]
set_input_transition -max 0.5  [get_ports {V[24]}]
set_input_transition -min 0.5  [get_ports {V[24]}]
set_input_transition -max 0.5  [get_ports {V[23]}]
set_input_transition -min 0.5  [get_ports {V[23]}]
set_input_transition -max 0.5  [get_ports {V[22]}]
set_input_transition -min 0.5  [get_ports {V[22]}]
set_input_transition -max 0.5  [get_ports {V[21]}]
set_input_transition -min 0.5  [get_ports {V[21]}]
set_input_transition -max 0.5  [get_ports {V[20]}]
set_input_transition -min 0.5  [get_ports {V[20]}]
set_input_transition -max 0.5  [get_ports {V[19]}]
set_input_transition -min 0.5  [get_ports {V[19]}]
set_input_transition -max 0.5  [get_ports {V[18]}]
set_input_transition -min 0.5  [get_ports {V[18]}]
set_input_transition -max 0.5  [get_ports {V[17]}]
set_input_transition -min 0.5  [get_ports {V[17]}]
set_input_transition -max 0.5  [get_ports {V[16]}]
set_input_transition -min 0.5  [get_ports {V[16]}]
set_input_transition -max 0.5  [get_ports {V[15]}]
set_input_transition -min 0.5  [get_ports {V[15]}]
set_input_transition -max 0.5  [get_ports {V[14]}]
set_input_transition -min 0.5  [get_ports {V[14]}]
set_input_transition -max 0.5  [get_ports {V[13]}]
set_input_transition -min 0.5  [get_ports {V[13]}]
set_input_transition -max 0.5  [get_ports {V[12]}]
set_input_transition -min 0.5  [get_ports {V[12]}]
set_input_transition -max 0.5  [get_ports {V[11]}]
set_input_transition -min 0.5  [get_ports {V[11]}]
set_input_transition -max 0.5  [get_ports {V[10]}]
set_input_transition -min 0.5  [get_ports {V[10]}]
set_input_transition -max 0.5  [get_ports {V[9]}]
set_input_transition -min 0.5  [get_ports {V[9]}]
set_input_transition -max 0.5  [get_ports {V[8]}]
set_input_transition -min 0.5  [get_ports {V[8]}]
set_input_transition -max 0.5  [get_ports {V[7]}]
set_input_transition -min 0.5  [get_ports {V[7]}]
set_input_transition -max 0.5  [get_ports {V[6]}]
set_input_transition -min 0.5  [get_ports {V[6]}]
set_input_transition -max 0.5  [get_ports {V[5]}]
set_input_transition -min 0.5  [get_ports {V[5]}]
set_input_transition -max 0.5  [get_ports {V[4]}]
set_input_transition -min 0.5  [get_ports {V[4]}]
set_input_transition -max 0.5  [get_ports {V[3]}]
set_input_transition -min 0.5  [get_ports {V[3]}]
set_input_transition -max 0.5  [get_ports {V[2]}]
set_input_transition -min 0.5  [get_ports {V[2]}]
set_input_transition -max 0.5  [get_ports {V[1]}]
set_input_transition -min 0.5  [get_ports {V[1]}]
set_input_transition -max 0.5  [get_ports {V[0]}]
set_input_transition -min 0.5  [get_ports {V[0]}]
set_input_transition -max 0.5  [get_ports {out_weight[31]}]
set_input_transition -min 0.5  [get_ports {out_weight[31]}]
set_input_transition -max 0.5  [get_ports {out_weight[30]}]
set_input_transition -min 0.5  [get_ports {out_weight[30]}]
set_input_transition -max 0.5  [get_ports {out_weight[29]}]
set_input_transition -min 0.5  [get_ports {out_weight[29]}]
set_input_transition -max 0.5  [get_ports {out_weight[28]}]
set_input_transition -min 0.5  [get_ports {out_weight[28]}]
set_input_transition -max 0.5  [get_ports {out_weight[27]}]
set_input_transition -min 0.5  [get_ports {out_weight[27]}]
set_input_transition -max 0.5  [get_ports {out_weight[26]}]
set_input_transition -min 0.5  [get_ports {out_weight[26]}]
set_input_transition -max 0.5  [get_ports {out_weight[25]}]
set_input_transition -min 0.5  [get_ports {out_weight[25]}]
set_input_transition -max 0.5  [get_ports {out_weight[24]}]
set_input_transition -min 0.5  [get_ports {out_weight[24]}]
set_input_transition -max 0.5  [get_ports {out_weight[23]}]
set_input_transition -min 0.5  [get_ports {out_weight[23]}]
set_input_transition -max 0.5  [get_ports {out_weight[22]}]
set_input_transition -min 0.5  [get_ports {out_weight[22]}]
set_input_transition -max 0.5  [get_ports {out_weight[21]}]
set_input_transition -min 0.5  [get_ports {out_weight[21]}]
set_input_transition -max 0.5  [get_ports {out_weight[20]}]
set_input_transition -min 0.5  [get_ports {out_weight[20]}]
set_input_transition -max 0.5  [get_ports {out_weight[19]}]
set_input_transition -min 0.5  [get_ports {out_weight[19]}]
set_input_transition -max 0.5  [get_ports {out_weight[18]}]
set_input_transition -min 0.5  [get_ports {out_weight[18]}]
set_input_transition -max 0.5  [get_ports {out_weight[17]}]
set_input_transition -min 0.5  [get_ports {out_weight[17]}]
set_input_transition -max 0.5  [get_ports {out_weight[16]}]
set_input_transition -min 0.5  [get_ports {out_weight[16]}]
set_input_transition -max 0.5  [get_ports {out_weight[15]}]
set_input_transition -min 0.5  [get_ports {out_weight[15]}]
set_input_transition -max 0.5  [get_ports {out_weight[14]}]
set_input_transition -min 0.5  [get_ports {out_weight[14]}]
set_input_transition -max 0.5  [get_ports {out_weight[13]}]
set_input_transition -min 0.5  [get_ports {out_weight[13]}]
set_input_transition -max 0.5  [get_ports {out_weight[12]}]
set_input_transition -min 0.5  [get_ports {out_weight[12]}]
set_input_transition -max 0.5  [get_ports {out_weight[11]}]
set_input_transition -min 0.5  [get_ports {out_weight[11]}]
set_input_transition -max 0.5  [get_ports {out_weight[10]}]
set_input_transition -min 0.5  [get_ports {out_weight[10]}]
set_input_transition -max 0.5  [get_ports {out_weight[9]}]
set_input_transition -min 0.5  [get_ports {out_weight[9]}]
set_input_transition -max 0.5  [get_ports {out_weight[8]}]
set_input_transition -min 0.5  [get_ports {out_weight[8]}]
set_input_transition -max 0.5  [get_ports {out_weight[7]}]
set_input_transition -min 0.5  [get_ports {out_weight[7]}]
set_input_transition -max 0.5  [get_ports {out_weight[6]}]
set_input_transition -min 0.5  [get_ports {out_weight[6]}]
set_input_transition -max 0.5  [get_ports {out_weight[5]}]
set_input_transition -min 0.5  [get_ports {out_weight[5]}]
set_input_transition -max 0.5  [get_ports {out_weight[4]}]
set_input_transition -min 0.5  [get_ports {out_weight[4]}]
set_input_transition -max 0.5  [get_ports {out_weight[3]}]
set_input_transition -min 0.5  [get_ports {out_weight[3]}]
set_input_transition -max 0.5  [get_ports {out_weight[2]}]
set_input_transition -min 0.5  [get_ports {out_weight[2]}]
set_input_transition -max 0.5  [get_ports {out_weight[1]}]
set_input_transition -min 0.5  [get_ports {out_weight[1]}]
set_input_transition -max 0.5  [get_ports {out_weight[0]}]
set_input_transition -min 0.5  [get_ports {out_weight[0]}]
