###################################################################

# Created by write_sdc on Fri Oct  9 04:00:51 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_load -pin_load 0.05 [get_ports out_valid]
set_load -pin_load 0.05 [get_ports {chain_num[6]}]
set_load -pin_load 0.05 [get_ports {chain_num[5]}]
set_load -pin_load 0.05 [get_ports {chain_num[4]}]
set_load -pin_load 0.05 [get_ports {chain_num[3]}]
set_load -pin_load 0.05 [get_ports {chain_num[2]}]
set_load -pin_load 0.05 [get_ports {chain_num[1]}]
set_load -pin_load 0.05 [get_ports {chain_num[0]}]
set_load -pin_load 0.05 [get_ports {elim_color[2]}]
set_load -pin_load 0.05 [get_ports {elim_color[1]}]
set_load -pin_load 0.05 [get_ports {elim_color[0]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[8]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[7]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[6]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[5]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[4]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[3]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[2]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[1]}]
set_load -pin_load 0.05 [get_ports {elim_cnt[0]}]
set_max_capacitance 0.15 [get_ports clk]
set_max_capacitance 0.15 [get_ports rst_n]
set_max_capacitance 0.15 [get_ports in_valid]
set_max_capacitance 0.15 [get_ports {ring_len[7]}]
set_max_capacitance 0.15 [get_ports {ring_len[6]}]
set_max_capacitance 0.15 [get_ports {ring_len[5]}]
set_max_capacitance 0.15 [get_ports {ring_len[4]}]
set_max_capacitance 0.15 [get_ports {ring_len[3]}]
set_max_capacitance 0.15 [get_ports {ring_len[2]}]
set_max_capacitance 0.15 [get_ports {ring_len[1]}]
set_max_capacitance 0.15 [get_ports {ring_len[0]}]
set_max_capacitance 0.15 [get_ports {in_color[2]}]
set_max_capacitance 0.15 [get_ports {in_color[1]}]
set_max_capacitance 0.15 [get_ports {in_color[0]}]
set_max_capacitance 0.15 [get_ports shot_valid]
set_max_capacitance 0.15 [get_ports {shot_color[2]}]
set_max_capacitance 0.15 [get_ports {shot_color[1]}]
set_max_capacitance 0.15 [get_ports {shot_color[0]}]
set_max_capacitance 0.15 [get_ports {shot_pos[7]}]
set_max_capacitance 0.15 [get_ports {shot_pos[6]}]
set_max_capacitance 0.15 [get_ports {shot_pos[5]}]
set_max_capacitance 0.15 [get_ports {shot_pos[4]}]
set_max_capacitance 0.15 [get_ports {shot_pos[3]}]
set_max_capacitance 0.15 [get_ports {shot_pos[2]}]
set_max_capacitance 0.15 [get_ports {shot_pos[1]}]
set_max_capacitance 0.15 [get_ports {shot_pos[0]}]
set_max_fanout 10 [get_ports clk]
set_max_fanout 10 [get_ports rst_n]
set_max_fanout 10 [get_ports in_valid]
set_max_fanout 10 [get_ports {ring_len[7]}]
set_max_fanout 10 [get_ports {ring_len[6]}]
set_max_fanout 10 [get_ports {ring_len[5]}]
set_max_fanout 10 [get_ports {ring_len[4]}]
set_max_fanout 10 [get_ports {ring_len[3]}]
set_max_fanout 10 [get_ports {ring_len[2]}]
set_max_fanout 10 [get_ports {ring_len[1]}]
set_max_fanout 10 [get_ports {ring_len[0]}]
set_max_fanout 10 [get_ports {in_color[2]}]
set_max_fanout 10 [get_ports {in_color[1]}]
set_max_fanout 10 [get_ports {in_color[0]}]
set_max_fanout 10 [get_ports shot_valid]
set_max_fanout 10 [get_ports {shot_color[2]}]
set_max_fanout 10 [get_ports {shot_color[1]}]
set_max_fanout 10 [get_ports {shot_color[0]}]
set_max_fanout 10 [get_ports {shot_pos[7]}]
set_max_fanout 10 [get_ports {shot_pos[6]}]
set_max_fanout 10 [get_ports {shot_pos[5]}]
set_max_fanout 10 [get_ports {shot_pos[4]}]
set_max_fanout 10 [get_ports {shot_pos[3]}]
set_max_fanout 10 [get_ports {shot_pos[2]}]
set_max_fanout 10 [get_ports {shot_pos[1]}]
set_max_fanout 10 [get_ports {shot_pos[0]}]
set_max_transition 3 [get_ports clk]
set_max_transition 3 [get_ports rst_n]
set_max_transition 3 [get_ports in_valid]
set_max_transition 3 [get_ports {ring_len[7]}]
set_max_transition 3 [get_ports {ring_len[6]}]
set_max_transition 3 [get_ports {ring_len[5]}]
set_max_transition 3 [get_ports {ring_len[4]}]
set_max_transition 3 [get_ports {ring_len[3]}]
set_max_transition 3 [get_ports {ring_len[2]}]
set_max_transition 3 [get_ports {ring_len[1]}]
set_max_transition 3 [get_ports {ring_len[0]}]
set_max_transition 3 [get_ports {in_color[2]}]
set_max_transition 3 [get_ports {in_color[1]}]
set_max_transition 3 [get_ports {in_color[0]}]
set_max_transition 3 [get_ports shot_valid]
set_max_transition 3 [get_ports {shot_color[2]}]
set_max_transition 3 [get_ports {shot_color[1]}]
set_max_transition 3 [get_ports {shot_color[0]}]
set_max_transition 3 [get_ports {shot_pos[7]}]
set_max_transition 3 [get_ports {shot_pos[6]}]
set_max_transition 3 [get_ports {shot_pos[5]}]
set_max_transition 3 [get_ports {shot_pos[4]}]
set_max_transition 3 [get_ports {shot_pos[3]}]
set_max_transition 3 [get_ports {shot_pos[2]}]
set_max_transition 3 [get_ports {shot_pos[1]}]
set_max_transition 3 [get_ports {shot_pos[0]}]
create_clock [get_ports clk]  -period 2.7  -waveform {0 1.35}
set_clock_uncertainty 0.1  [get_clocks clk]
set_clock_transition -max -rise 0.1 [get_clocks clk]
set_clock_transition -max -fall 0.1 [get_clocks clk]
set_clock_transition -min -rise 0.1 [get_clocks clk]
set_clock_transition -min -fall 0.1 [get_clocks clk]
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  -max 1.35  [get_ports in_valid]
set_input_delay -clock clk  -min 0  [get_ports in_valid]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[7]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[7]}]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[6]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[6]}]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[5]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[5]}]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[4]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[4]}]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[3]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[3]}]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[2]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[2]}]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[1]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[1]}]
set_input_delay -clock clk  -max 1.35  [get_ports {ring_len[0]}]
set_input_delay -clock clk  -min 0  [get_ports {ring_len[0]}]
set_input_delay -clock clk  -max 1.35  [get_ports {in_color[2]}]
set_input_delay -clock clk  -min 0  [get_ports {in_color[2]}]
set_input_delay -clock clk  -max 1.35  [get_ports {in_color[1]}]
set_input_delay -clock clk  -min 0  [get_ports {in_color[1]}]
set_input_delay -clock clk  -max 1.35  [get_ports {in_color[0]}]
set_input_delay -clock clk  -min 0  [get_ports {in_color[0]}]
set_input_delay -clock clk  -max 1.35  [get_ports shot_valid]
set_input_delay -clock clk  -min 0  [get_ports shot_valid]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_color[2]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_color[2]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_color[1]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_color[1]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_color[0]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_color[0]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[7]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[7]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[6]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[6]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[5]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[5]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[4]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[4]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[3]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[3]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[2]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[2]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[1]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[1]}]
set_input_delay -clock clk  -max 1.35  [get_ports {shot_pos[0]}]
set_input_delay -clock clk  -min 0  [get_ports {shot_pos[0]}]
set_output_delay -clock clk  -max 1.35  [get_ports out_valid]
set_output_delay -clock clk  -min 0  [get_ports out_valid]
set_output_delay -clock clk  -max 1.35  [get_ports {chain_num[6]}]
set_output_delay -clock clk  -min 0  [get_ports {chain_num[6]}]
set_output_delay -clock clk  -max 1.35  [get_ports {chain_num[5]}]
set_output_delay -clock clk  -min 0  [get_ports {chain_num[5]}]
set_output_delay -clock clk  -max 1.35  [get_ports {chain_num[4]}]
set_output_delay -clock clk  -min 0  [get_ports {chain_num[4]}]
set_output_delay -clock clk  -max 1.35  [get_ports {chain_num[3]}]
set_output_delay -clock clk  -min 0  [get_ports {chain_num[3]}]
set_output_delay -clock clk  -max 1.35  [get_ports {chain_num[2]}]
set_output_delay -clock clk  -min 0  [get_ports {chain_num[2]}]
set_output_delay -clock clk  -max 1.35  [get_ports {chain_num[1]}]
set_output_delay -clock clk  -min 0  [get_ports {chain_num[1]}]
set_output_delay -clock clk  -max 1.35  [get_ports {chain_num[0]}]
set_output_delay -clock clk  -min 0  [get_ports {chain_num[0]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_color[2]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_color[2]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_color[1]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_color[1]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_color[0]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_color[0]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[8]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[8]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[7]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[7]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[6]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[6]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[5]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[5]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[4]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[4]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[3]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[3]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[2]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[2]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[1]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[1]}]
set_output_delay -clock clk  -max 1.35  [get_ports {elim_cnt[0]}]
set_output_delay -clock clk  -min 0  [get_ports {elim_cnt[0]}]
set_input_transition -max 0.5  [get_ports clk]
set_input_transition -min 0.5  [get_ports clk]
set_input_transition -max 0.5  [get_ports rst_n]
set_input_transition -min 0.5  [get_ports rst_n]
set_input_transition -max 0.5  [get_ports in_valid]
set_input_transition -min 0.5  [get_ports in_valid]
set_input_transition -max 0.5  [get_ports {ring_len[7]}]
set_input_transition -min 0.5  [get_ports {ring_len[7]}]
set_input_transition -max 0.5  [get_ports {ring_len[6]}]
set_input_transition -min 0.5  [get_ports {ring_len[6]}]
set_input_transition -max 0.5  [get_ports {ring_len[5]}]
set_input_transition -min 0.5  [get_ports {ring_len[5]}]
set_input_transition -max 0.5  [get_ports {ring_len[4]}]
set_input_transition -min 0.5  [get_ports {ring_len[4]}]
set_input_transition -max 0.5  [get_ports {ring_len[3]}]
set_input_transition -min 0.5  [get_ports {ring_len[3]}]
set_input_transition -max 0.5  [get_ports {ring_len[2]}]
set_input_transition -min 0.5  [get_ports {ring_len[2]}]
set_input_transition -max 0.5  [get_ports {ring_len[1]}]
set_input_transition -min 0.5  [get_ports {ring_len[1]}]
set_input_transition -max 0.5  [get_ports {ring_len[0]}]
set_input_transition -min 0.5  [get_ports {ring_len[0]}]
set_input_transition -max 0.5  [get_ports {in_color[2]}]
set_input_transition -min 0.5  [get_ports {in_color[2]}]
set_input_transition -max 0.5  [get_ports {in_color[1]}]
set_input_transition -min 0.5  [get_ports {in_color[1]}]
set_input_transition -max 0.5  [get_ports {in_color[0]}]
set_input_transition -min 0.5  [get_ports {in_color[0]}]
set_input_transition -max 0.5  [get_ports shot_valid]
set_input_transition -min 0.5  [get_ports shot_valid]
set_input_transition -max 0.5  [get_ports {shot_color[2]}]
set_input_transition -min 0.5  [get_ports {shot_color[2]}]
set_input_transition -max 0.5  [get_ports {shot_color[1]}]
set_input_transition -min 0.5  [get_ports {shot_color[1]}]
set_input_transition -max 0.5  [get_ports {shot_color[0]}]
set_input_transition -min 0.5  [get_ports {shot_color[0]}]
set_input_transition -max 0.5  [get_ports {shot_pos[7]}]
set_input_transition -min 0.5  [get_ports {shot_pos[7]}]
set_input_transition -max 0.5  [get_ports {shot_pos[6]}]
set_input_transition -min 0.5  [get_ports {shot_pos[6]}]
set_input_transition -max 0.5  [get_ports {shot_pos[5]}]
set_input_transition -min 0.5  [get_ports {shot_pos[5]}]
set_input_transition -max 0.5  [get_ports {shot_pos[4]}]
set_input_transition -min 0.5  [get_ports {shot_pos[4]}]
set_input_transition -max 0.5  [get_ports {shot_pos[3]}]
set_input_transition -min 0.5  [get_ports {shot_pos[3]}]
set_input_transition -max 0.5  [get_ports {shot_pos[2]}]
set_input_transition -min 0.5  [get_ports {shot_pos[2]}]
set_input_transition -max 0.5  [get_ports {shot_pos[1]}]
set_input_transition -min 0.5  [get_ports {shot_pos[1]}]
set_input_transition -max 0.5  [get_ports {shot_pos[0]}]
set_input_transition -min 0.5  [get_ports {shot_pos[0]}]
